<?php
declare(strict_types=1);

return array(
	'framework.plugin-architecture' => array( 'path' => 'tests/architecture/run-plugin-architecture-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.lifecycle-contract' => array( 'path' => 'tests/shipments/run-shipment-lifecycle-contract-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.admin-ajax' => array( 'path' => 'tests/shipments/run-shipment-admin-ajax-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.admin-js-structure' => array( 'path' => 'tests/shipments/run-shipment-admin-js-structure-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.modal-extensions' => array( 'path' => 'tests/shipments/run-shipment-modal-extensions-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.document-actions' => array( 'path' => 'tests/shipments/run-shipment-document-actions-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.persistence-mappers' => array( 'path' => 'tests/shipments/run-shipment-persistence-mappers-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.actual-cost-service' => array( 'path' => 'tests/shipments/run-shipment-actual-cost-service-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.actual-cost-presentation' => array( 'path' => 'tests/shipments/run-shipment-actual-cost-presentation-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.cost-threshold-policy' => array( 'path' => 'tests/shipments/run-shipment-cost-threshold-policy-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.cost-analytics-storage' => array( 'path' => 'tests/shipments/run-shipment-cost-analytics-storage-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.cost-analytics-indexer' => array( 'path' => 'tests/shipments/run-shipment-cost-analytics-indexer-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.cost-analytics-query' => array( 'path' => 'tests/shipments/run-shipment-cost-analytics-query-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.cost-analytics' => array( 'path' => 'tests/shipments/run-shipment-cost-analytics-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.allocation' => array( 'path' => 'tests/shipments/run-shipment-allocation-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.status' => array( 'path' => 'tests/shipments/run-shipment-status-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.adapter-registry' => array( 'path' => 'tests/shipments/run-carrier-adapter-registry-smoke.php', 'groups' => array( 'framework' ) ),
	'framework.pickup-provider-registry' => array( 'path' => 'tests/pickup/run-carrier-pickup-provider-registry-smoke.php', 'groups' => array( 'framework' ) ),

	'russian-post.shipments' => array( 'path' => 'tests/shipments/run-russian-post-shipments-smoke.php', 'groups' => array( 'russian-post' ) ),
	'russian-post.price' => array( 'path' => 'tests/shipments/run-russian-post-shipment-price-smoke.php', 'groups' => array( 'russian-post' ) ),
	'russian-post.cancel' => array( 'path' => 'tests/shipments/run-russian-post-cancel-shipment-smoke.php', 'groups' => array( 'russian-post' ) ),
	'russian-post.documents' => array( 'path' => 'tests/shipments/run-russian-post-documents-smoke.php', 'groups' => array( 'russian-post' ) ),
	'russian-post.pickup-import' => array( 'path' => 'tests/pickup/run-russian-post-pickup-import-smoke.php', 'groups' => array( 'russian-post' ) ),

	'cdek.foundation' => array( 'path' => 'tests/cdek/run-cdek-foundation-smoke.php', 'groups' => array( 'cdek' ) ),
	'cdek.order-creation' => array( 'path' => 'tests/cdek/run-cdek-order-creation-smoke.php', 'groups' => array( 'cdek' ), 'timeout' => 120 ),
	'cdek.eaeu' => array( 'path' => 'tests/cdek/run-cdek-eaeu-smoke.php', 'groups' => array( 'cdek' ) ),
	'cdek.tariff-calculation' => array( 'path' => 'tests/cdek/run-cdek-tariff-calculation-smoke.php', 'groups' => array( 'cdek' ), 'timeout' => 120 ),
	'cdek.tariffs-sync' => array( 'path' => 'tests/cdek/run-cdek-tariffs-sync-smoke.php', 'groups' => array( 'cdek' ) ),

	'dpd.foundation' => array( 'path' => 'tests/dpd/run-dpd-foundation-smoke.php', 'groups' => array( 'dpd' ) ),
	'dpd.create-order' => array( 'path' => 'tests/dpd/run-dpd-create-order-smoke.php', 'groups' => array( 'dpd' ), 'timeout' => 120 ),
	'dpd.shipment-lifecycle' => array( 'path' => 'tests/dpd/run-dpd-shipment-lifecycle-smoke.php', 'groups' => array( 'dpd' ) ),
	'dpd.shipment-buttons' => array( 'path' => 'tests/dpd/run-dpd-shipment-buttons-smoke.php', 'groups' => array( 'dpd' ) ),
	'dpd.status-mapping' => array( 'path' => 'tests/dpd/run-dpd-status-mapping-smoke.php', 'groups' => array( 'dpd' ) ),
	'dpd.documents' => array( 'path' => 'tests/dpd/run-dpd-documents-smoke.php', 'groups' => array( 'dpd' ) ),
	'dpd.event-sync' => array( 'path' => 'tests/dpd/run-dpd-event-sync-smoke.php', 'groups' => array( 'dpd' ) ),
	'dpd.status-autosync' => array( 'path' => 'tests/dpd/run-dpd-autosync-smoke.php', 'groups' => array( 'dpd' ) ),

	'yandex.checkout-rates' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-checkout-rates-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.foundation' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-foundation-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.geo-pipeline-v2' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-geo-pipeline-v2-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.geo-v2-builder' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-geo-v2-builder-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.geo-v2-region-enrichment' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-geo-v2-region-enrichment-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.location-mapping-v2' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-location-mapping-v2-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.pickup-selection' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-pickup-selection-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.pickup-v2-foundation' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-pickup-v2-foundation-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.pickup-v2-runner' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-pickup-v2-runner-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.pricing-calculator' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-pricing-calculator-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.region-mapping-v2' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-region-mapping-v2-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.shipment-framework' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-shipment-framework-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.shipment-http' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-shipment-http-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.shipment-payload' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-shipment-payload-smoke.php', 'groups' => array( 'yandex' ) ),
	'yandex.source-station' => array( 'path' => 'tests/yandex-delivery/run-yandex-delivery-source-station-smoke.php', 'groups' => array( 'yandex' ) ),

	'jet-logistic.foundation' => array( 'path' => 'tests/jet-logistic/run-jet-logistic-smoke.php', 'groups' => array( 'jet-logistic' ) ),
	'pek.foundation' => array( 'path' => 'tests/pek/run-pek-foundation-smoke.php', 'groups' => array( 'pek' ) ),
	'pek.admin-routing' => array( 'path' => 'tests/pek/run-pek-admin-routing-smoke.php', 'groups' => array( 'pek' ) ),
	'pek.admin-ui' => array( 'path' => 'tests/pek/run-pek-admin-ui-smoke.php', 'groups' => array( 'pek' ) ),
	'pek.warehouse-datetime' => array( 'path' => 'tests/pek/run-pek-warehouse-datetime-smoke.php', 'groups' => array( 'pek' ) ),
	'pek.schema-integrity' => array( 'path' => 'tests/pek/run-pek-schema-integrity-smoke.php', 'groups' => array( 'pek' ) ),
	'pek.geography' => array( 'path' => 'tests/pek/run-pek-geography-smoke.php', 'groups' => array( 'pek' ) ),
	'pek.pickup-provider' => array( 'path' => 'tests/pek/run-pek-pickup-provider-smoke.php', 'groups' => array( 'pek' ) ),

	'status.order-status-mapping' => array( 'path' => 'tests/statuses/run-order-status-mapping-smoke.php', 'groups' => array( 'status-core' ) ),
	'status.status-autosync' => array( 'path' => 'tests/statuses/run-status-autosync-smoke.php', 'groups' => array( 'status-core' ) ),
	'core.packaging' => array( 'path' => 'tests/packaging/run-packaging-smoke.php', 'groups' => array( 'status-core' ) ),
	'core.checkout' => array( 'path' => 'tests/checkout/run-checkout-smoke.php', 'groups' => array( 'status-core' ) ),
	'core.woocommerce-checkout' => array( 'path' => 'tests/checkout/run-woocommerce-checkout-smoke.php', 'groups' => array( 'status-core' ) ),
	'core.checkout-location-picker' => array( 'path' => 'tests/checkout/run-checkout-location-picker-smoke.php', 'groups' => array( 'status-core' ) ),
	'core.runtime-stabilization' => array( 'path' => 'tests/checkout/run-runtime-stabilization-smoke.php', 'groups' => array( 'status-core' ) ),
	'core.order-delivery-recalculation' => array( 'path' => 'tests/orders/run-order-delivery-recalculation-smoke.php', 'groups' => array( 'status-core' ) ),

	'baseline.dpd-shipment-preparation' => array(
		'path' => 'tests/dpd/run-dpd-shipment-preparation-smoke.php',
		'groups' => array( 'baseline' ),
		'required' => false,
		'baseline' => true,
		'expected_failure' => 'DPD dry-run payload must include request.header.datePickup.',
	),
	'baseline.cdek-pickup-points' => array(
		'path' => 'tests/cdek/run-cdek-pickup-points-smoke.php',
		'groups' => array( 'baseline' ),
		'required' => false,
		'baseline' => true,
		'expected_failure' => 'Checkout pickup map must render every CDEK point returned by backend',
		'timeout' => 120,
	),
	'optional.russian-post-carrier' => array(
		'path' => 'tests/carriers/run-russian-post-smoke.php',
		'groups' => array( 'optional' ),
		'required' => false,
		'optional' => true,
		'expected_failure' => 'Class "WC_Shipping_Method" not found',
	),
	'optional.russian-post-domestic-carrier' => array(
		'path' => 'tests/carriers/run-russian-post-domestic-smoke.php',
		'groups' => array( 'optional' ),
		'required' => false,
		'optional' => true,
		'expected_failure' => 'Typed property WallsShop\\WDC\\Checkout\\WooCommerce\\NewShippingMethod::$settings_repository must not be accessed before initialization',
	),
);
