<?php
declare(strict_types=1);

namespace WallsShop\WDC\Shipments\RussianPost;

use WallsShop\WDC\Domain\Status\DeliveryStatus;
use WallsShop\WDC\Infrastructure\Settings\SettingsRepository;

defined( 'ABSPATH' ) || exit;

final class RussianPostTrackingStatusMapper {
	public const MAPPING_KEY = 'russian_post_status_mapping';

	/**
	 * Native labels and terminal metadata come from the official Russian Post
	 * tracking dictionary snapshot retrieved on 2026-09-12. Universal statuses
	 * preserve the 1.0.10 production mapping; newly published keys default to
	 * UNKNOWN so the upgrade cannot advance shipment state unexpectedly.
	 *
	 * @see https://tracking.pochta.ru/support/dictionaries/operation_codes
	 * @var array<string,array{label:string,status:string,terminal:bool}>
	 */
	private const CATALOG = array(
		'1:1' => array( 'label' => 'Прием — Единичный', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:2' => array( 'label' => 'Прием — Партионный', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:3' => array( 'label' => 'Прием — Партионный электронно', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:4' => array( 'label' => 'Прием — Упрощенный единичный', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:5' => array( 'label' => 'Прием — По ведомости в РЦ (распределительном центре)', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:6' => array( 'label' => 'Прием — По ведомости в СЦ (сортировочном центре)', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:7' => array( 'label' => 'Прием — Упрощенный предзаполненный', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:8' => array( 'label' => 'Прием — Упрощенный предоплаченный', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:9' => array( 'label' => 'Прием — В соответствие с Поручением экспедитору', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:10' => array( 'label' => 'Прием — По поручению адресата', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:11' => array( 'label' => 'Прием — Партионный почтальоном', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:12' => array( 'label' => 'Прием — В СЦ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'2:1' => array( 'label' => 'Вручение — Вручение адресату', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:2' => array( 'label' => 'Вручение — Вручение отправителю', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:3' => array( 'label' => 'Вручение — Выдано адресату через почтомат', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:4' => array( 'label' => 'Вручение — Выдано отправителю через почтомат', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:5' => array( 'label' => 'Вручение — Адресату электронно', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:6' => array( 'label' => 'Вручение — Адресату почтальоном', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:7' => array( 'label' => 'Вручение — Отправителю почтальоном', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:8' => array( 'label' => 'Вручение — Адресату курьером', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:9' => array( 'label' => 'Вручение — Отправителю курьером', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:10' => array( 'label' => 'Вручение — Адресату с контролем ответа', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:11' => array( 'label' => 'Вручение — Адресату с контролем ответа почтальоном', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:12' => array( 'label' => 'Вручение — Адресату с контролем ответа курьером', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:13' => array( 'label' => 'Вручение — Вручение адресату по ПЭП', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:14' => array( 'label' => 'Вручение — Для передачи на оцифровку', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:15' => array( 'label' => 'Вручение — Адресату Экспедитором', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:16' => array( 'label' => 'Вручение — Отправителю Экспедитором', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:17' => array( 'label' => 'Вручение — Адресату почтальоном по ПЭП', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:18' => array( 'label' => 'Вручение — Адресату курьером по ПЭП', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:19' => array( 'label' => 'Вручение — Вручение адресату роботом-курьером', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:20' => array( 'label' => 'Вручение — Вручение отправителю роботом-курьером', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:21' => array( 'label' => 'Вручение — Вручение адресату через ААПС', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:22' => array( 'label' => 'Вручение — Вручение отправителю через ААПС', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:23' => array( 'label' => 'Вручение — Вручение адресату через АПШ', 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:24' => array( 'label' => 'Вручение — Вручение отправителю через АПШ', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		// Compatibility exception: the current Russian Post dictionary marks 2:25
		// as terminal, while WDC 1.0.10 treated it as non-terminal. Keep false to
		// avoid changing shipment lifecycle semantics in the mapping UI release.
		'2:25' => array( 'label' => 'Вручение — Адресату по QR коду', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:26' => array( 'label' => 'Вручение — Адресату почтальоном по QR коду', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:27' => array( 'label' => 'Вручение — Адресату курьером по QR коду', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:28' => array( 'label' => 'Вручение — Отправителю по QR коду', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:29' => array( 'label' => 'Вручение — Отправителю почтальоном по QR коду', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:30' => array( 'label' => 'Вручение — Отправителю курьером по QR коду', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:31' => array( 'label' => 'Вручение — Отправителю курьером по ПЭП', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:32' => array( 'label' => 'Вручение — Адресату по пин-коду', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:33' => array( 'label' => 'Вручение — Отправителю по пин-коду', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:34' => array( 'label' => 'Вручение — Вручение через Бокс-сервис получателю', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:35' => array( 'label' => 'Вручение — Вручение через Бокс-сервис отправителю', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:36' => array( 'label' => 'Вручение — Вручение адресату через почтовый ящик', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:37' => array( 'label' => 'Вручение — Вручение отправителю через почтовый ящик', 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'3:1' => array( 'label' => 'Возврат — Истек срок хранения', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:2' => array( 'label' => 'Возврат — Заявление отправителя', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:3' => array( 'label' => 'Возврат — Отсутствие адресата по указанному адресу', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:4' => array( 'label' => 'Возврат — Отказ адресата', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:5' => array( 'label' => 'Возврат — Смерть адресата', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:6' => array( 'label' => 'Возврат — Невозможно прочесть адрес адресата', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:7' => array( 'label' => 'Возврат — Отказ в выпуске таможней', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:8' => array( 'label' => 'Возврат — Адресат, абонирующий абонементный почтовый шкаф, не указан или указан неправильно', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:9' => array( 'label' => 'Возврат — Иные обстоятельства', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:10' => array( 'label' => 'Возврат — Неверный адрес', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:11' => array( 'label' => 'Возврат — Несоответствие комплектности', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:12' => array( 'label' => 'Возврат — Запрещено САБ', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:13' => array( 'label' => 'Возврат — Для проведения таможенных операций', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:14' => array( 'label' => 'Возврат — Распоряжение ЭТП', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:15' => array( 'label' => 'Возврат — Частичный выкуп', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:16' => array( 'label' => 'Возврат — По согласованию с адресатом', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:17' => array( 'label' => 'Возврат — Несоответствие возраста получателя "18+"', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:18' => array( 'label' => 'Возврат — ПВЗ закрыт', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:19' => array( 'label' => 'Возврат — Отказ ПВЗ в приеме', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:20' => array( 'label' => 'Возврат — Отсутствие беспрепятственного доступа к адресату', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:21' => array( 'label' => 'Возврат — Нет доступа к абонентским п/я или они неисправны', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:22' => array( 'label' => 'Возврат — Адрес отсутствует', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:23' => array( 'label' => 'Возврат — По причине дефектности', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'4:1' => array( 'label' => 'Досылка почты — По заявлению пользователя', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:2' => array( 'label' => 'Досылка почты — Выбытие адресата по новому адресу', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:3' => array( 'label' => 'Досылка почты — Засылка', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:4' => array( 'label' => 'Досылка почты — Запрещено САБ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:5' => array( 'label' => 'Досылка почты — Передача на временное хранение', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:6' => array( 'label' => 'Досылка почты — Передача в невостребованные', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:7' => array( 'label' => 'Досылка почты — По техническим причинам', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:8' => array( 'label' => 'Досылка почты — По согласованию с адресатом', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:9' => array( 'label' => 'Досылка почты — Отсутствует ПЭП', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:10' => array( 'label' => 'Досылка почты — Требуется оплата ТПО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:11' => array( 'label' => 'Досылка почты — Дефектность отправления', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:12' => array( 'label' => 'Досылка почты — Превышение габаритных размеров', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:13' => array( 'label' => 'Досылка почты — Досыл в адресное ОПС из АПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:14' => array( 'label' => 'Досылка почты — Нет свободных ячеек', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:15' => array( 'label' => 'Досылка почты — ПЭП подключен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:16' => array( 'label' => 'Досылка почты — ТПО оплачен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:17' => array( 'label' => 'Досылка почты — ПЭП подключен и ТПО оплачен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:18' => array( 'label' => 'Досылка почты — По заявлению пользователя на конкретное РПО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:19' => array( 'label' => 'Досылка почты — По заявлению адресата на все поступающие РПО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:20' => array( 'label' => 'Досылка почты — Переадресация Бокс-сервис', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'4:21' => array( 'label' => 'Досылка почты — Досыл с уведомлением', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'5:1' => array( 'label' => 'Невручение — Утрачено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'5:2' => array( 'label' => 'Невручение — Изъято', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'5:3' => array( 'label' => 'Невручение — Засылка', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'5:4' => array( 'label' => 'Невручение — Отказ подтверждения получения РПО через п/я', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'5:8' => array( 'label' => 'Невручение — Решение таможни', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'5:9' => array( 'label' => 'Невручение — (зарезервировано)', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:1' => array( 'label' => 'Хранение — До востребования', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:2' => array( 'label' => 'Хранение — На абонементный ящик', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:3' => array( 'label' => 'Хранение — Установленный срок хранения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:4' => array( 'label' => 'Хранение — Продление срока хранения по заявлению адресата', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:5' => array( 'label' => 'Хранение — Продление срока хранения по заявлению отправителя', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:1' => array( 'label' => 'Временное хранение — Нероздано', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:2' => array( 'label' => 'Временное хранение — Невостребовано', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:3' => array( 'label' => 'Временное хранение — Содержимое запрещено к пересылке', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:4' => array( 'label' => 'Временное хранение — Ожидает результаты экспертизы', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:0' => array( 'label' => 'Обработка — Сортировка', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:1' => array( 'label' => 'Обработка — Покинуло место приёма', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:2' => array( 'label' => 'Обработка — Прибыло в место вручения', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:3' => array( 'label' => 'Обработка — Прибыло в сортировочный центр', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:4' => array( 'label' => 'Обработка — Покинуло сортировочный центр', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:5' => array( 'label' => 'Обработка — Прибыло в место международного обмена', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:6' => array( 'label' => 'Обработка — Покинуло место международного обмена', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:7' => array( 'label' => 'Обработка — Прибыло в место транзита', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:8' => array( 'label' => 'Обработка — Покинуло место транзита', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:9' => array( 'label' => 'Обработка — Прибыло в почтомат', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:10' => array( 'label' => 'Обработка — Истекает срок хранения в почтомате', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:11' => array( 'label' => 'Обработка — Переадресовано в почтомат', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:12' => array( 'label' => 'Обработка — Изъято из почтомата', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:13' => array( 'label' => 'Обработка — Прибыло на территорию РФ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:14' => array( 'label' => 'Обработка — Прибыло в Центр выдачи посылок', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:15' => array( 'label' => 'Обработка — Передано курьеру (водителю)', 'status' => DeliveryStatus::HANDED_TO_COURIER, 'terminal' => false ),
		'8:16' => array( 'label' => 'Обработка — Доставлено для вручения электронно', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:17' => array( 'label' => 'Обработка — Направлено в РЦГП/ИВЦ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:18' => array( 'label' => 'Обработка — Передано почтальону', 'status' => DeliveryStatus::HANDED_TO_COURIER, 'terminal' => false ),
		'8:19' => array( 'label' => 'Обработка — Передача в кладовую хранения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:20' => array( 'label' => 'Обработка — Покинуло место возврата/досылки', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:21' => array( 'label' => 'Обработка — Уточнение адреса', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:22' => array( 'label' => 'Обработка — Ожидает курьерской доставки', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:23' => array( 'label' => 'Обработка — Продление срока хранения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:24' => array( 'label' => 'Обработка — Направлено извещение', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:25' => array( 'label' => 'Обработка — Доставлено извещение', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:26' => array( 'label' => 'Обработка — Зарегистрировано с новым номером', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:27' => array( 'label' => 'Обработка — Истекает срок хранения (осталось 25 дней)', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:28' => array( 'label' => 'Обработка — Истекает срок хранения (осталось 5 дней)', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:29' => array( 'label' => 'Обработка — Находится на техническом исследовании', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:30' => array( 'label' => 'Обработка — Поступило в РЦГП/ИВЦ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:31' => array( 'label' => 'Обработка — Покинуло РЦГП/ИВЦ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:32' => array( 'label' => 'Обработка — Направлено в УКД', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:33' => array( 'label' => 'Обработка — Истекает срок хранения (осталось 23 дня)', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:34' => array( 'label' => 'Обработка — Доввод данных', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:35' => array( 'label' => 'Обработка — Истекает срок хранения (осталось 10 дней)', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:36' => array( 'label' => 'Обработка — Зарегистрировано заявление на возврат', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:37' => array( 'label' => 'Обработка — Зарегистрировано заявление отправителя на продление срока хранения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:38' => array( 'label' => 'Обработка — Зарегистрировано заявление адресата на продление срока хранения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:39' => array( 'label' => 'Обработка — Сдано в ПВЗ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:40' => array( 'label' => 'Обработка — Истек срок хранения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:41' => array( 'label' => 'Обработка — Возврат скомплектован', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:42' => array( 'label' => 'Обработка — Истекает срок хранения (остался 1 день)', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:43' => array( 'label' => 'Обработка — Истекает срок хранения (осталось 2 дня)', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:44' => array( 'label' => 'Обработка — Сдано в СЦ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:45' => array( 'label' => 'Обработка — Резерв', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:46' => array( 'label' => 'Обработка — Резерв', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:47' => array( 'label' => 'Обработка — Приостановлена обработка по 115-ФЗ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:48' => array( 'label' => 'Обработка — Присвоено место адресного хранения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:49' => array( 'label' => 'Обработка — Направлено в пункт выдачи', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:50' => array( 'label' => 'Обработка — Отправка запроса в Колл-центр', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:51' => array( 'label' => 'Обработка — Фиксация массы после таможенного осмотра', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:52' => array( 'label' => 'Обработка — Вручение разрешено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:53' => array( 'label' => 'Обработка — Вручение не разрешено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:54' => array( 'label' => 'Обработка — Бронирование ячейки почтомата, отправление в очереди', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:55' => array( 'label' => 'Обработка — Ячейка почтомата забронирована', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:56' => array( 'label' => 'Обработка — Хранение отправления в адресном ОПС 2 дня до окончания срока хранения', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:57' => array( 'label' => 'Обработка — Хранение отправления в адресном ОПС 5 дней после доставки в ОПС', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:58' => array( 'label' => 'Обработка — Хранение отправления в адресном ПВЗ 5 дней', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:59' => array( 'label' => 'Обработка — Хранение отправления в адресном ОПС 5 дней после доставки в ОПС', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:60' => array( 'label' => 'Обработка — Заложено в ячейку АПШ/ААПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:61' => array( 'label' => 'Обработка — Зарегистрировано заявление получателя на досыл', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:62' => array( 'label' => 'Обработка — Передано в клиентский зал', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:63' => array( 'label' => 'Обработка — Отправка заявки в КЦ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:64' => array( 'label' => 'Обработка — Изъятие из АПШ/ААПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:65' => array( 'label' => 'Обработка — Отправление отсутствует', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:66' => array( 'label' => 'Обработка — Запрос согласия на вручение через а/я', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:67' => array( 'label' => 'Обработка — Согласие на вручение через а/я', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:68' => array( 'label' => 'Обработка — Передано курьеру для доставки в АПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:69' => array( 'label' => 'Обработка — Передано курьеру для доставки в ПВЗ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:70' => array( 'label' => 'Обработка — Принято курьером для доставки в УКД', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:71' => array( 'label' => 'Обработка — Направлено в ОПС вручения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:72' => array( 'label' => 'Обработка — Направлено в УОПК', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:73' => array( 'label' => 'Обработка — Прибыло в УОПК', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:74' => array( 'label' => 'Обработка — Заложено в ячейку АПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:75' => array( 'label' => 'Обработка — Забор из АПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:76' => array( 'label' => 'Обработка — Вынужденная переадресация отправления в ОПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:77' => array( 'label' => 'Обработка — Принято курьером для доставки в СЦ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:78' => array( 'label' => 'Обработка — Запрос отмены', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:79' => array( 'label' => 'Обработка — Отправлено для вручения ЭТП', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:80' => array( 'label' => 'Обработка — Оплачено получателем, вручение разрешено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:81' => array( 'label' => 'Обработка — Разрешено вручение доставки', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:82' => array( 'label' => 'Обработка — Отказ в доставке почтальоном', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:83' => array( 'label' => 'Обработка — Регистрация отправления в ПВЗ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:84' => array( 'label' => 'Обработка — Отказ в приеме в ПВЗ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:85' => array( 'label' => 'Обработка — Отмена регистрации в ПВЗ', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:86' => array( 'label' => 'Обработка — Зарегистрировано заявление отправителя на переадресацию', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:87' => array( 'label' => 'Обработка — Зарегистрировано заявление адресата на переадресацию', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:88' => array( 'label' => 'Обработка — Заявление на корректировку данных адресата', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:89' => array( 'label' => 'Обработка — Выполнена корректировка данных адресата', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:90' => array( 'label' => 'Обработка — Заказ на изменение метода вручения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:91' => array( 'label' => 'Обработка — Изменение метода вручения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:92' => array( 'label' => 'Обработка — Подготовка к отправке', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:93' => array( 'label' => 'Обработка — Поступило от перевозчика', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:94' => array( 'label' => 'Обработка — Определен метод доставки "электронный"', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'8:95' => array( 'label' => 'Обработка — Определен метод доставки "на бумаге"', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'9:1' => array( 'label' => 'Импорт международной почты — Поступило приписано', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'9:2' => array( 'label' => 'Импорт международной почты — Поступило не приписано', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'10:-' => array( 'label' => 'Экспорт международной почты', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'11:-' => array( 'label' => 'Прием на таможню', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'12:1' => array( 'label' => 'Неудачная попытка вручения — Временное отсутствие адресата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:2' => array( 'label' => 'Неудачная попытка вручения — Доставка отложена по просьбе адресата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:3' => array( 'label' => 'Неудачная попытка вручения — Неполный адрес', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:4' => array( 'label' => 'Неудачная попытка вручения — Неправильный/нечитаемый/неполный адрес', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:5' => array( 'label' => 'Неудачная попытка вручения — Адресат выбыл', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:6' => array( 'label' => 'Неудачная попытка вручения — Адресат отказался от отправления', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:7' => array( 'label' => 'Неудачная попытка вручения — Форс-мажор/непредвиденные обстоятельства', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:8' => array( 'label' => 'Неудачная попытка вручения — Иная', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:9' => array( 'label' => 'Неудачная попытка вручения — Адресат заберет отправление сам', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:10' => array( 'label' => 'Неудачная попытка вручения — Адресат не доступен', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:11' => array( 'label' => 'Неудачная попытка вручения — Неудачная доставка', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:12' => array( 'label' => 'Неудачная попытка вручения — Истек срок хранения в почтомате', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:13' => array( 'label' => 'Неудачная попытка вручения — По требованию отправителя', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:14' => array( 'label' => 'Неудачная попытка вручения — Отправление повреждено и/или без вложения', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:15' => array( 'label' => 'Неудачная попытка вручения — В ожидании оплаты сбора', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:16' => array( 'label' => 'Неудачная попытка вручения — Адресат переехал', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:17' => array( 'label' => 'Неудачная попытка вручения — У адресата есть абонентский ящик', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:18' => array( 'label' => 'Неудачная попытка вручения — Нет доставки на дом', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:19' => array( 'label' => 'Неудачная попытка вручения — Не отвечает таможенным требованиям', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:20' => array( 'label' => 'Неудачная попытка вручения — Неполные/недостаточные/неверные документы', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:21' => array( 'label' => 'Неудачная попытка вручения — Невозможно связаться с клиентом', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:22' => array( 'label' => 'Неудачная попытка вручения — Адресат бастует', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:23' => array( 'label' => 'Неудачная попытка вручения — Запрещенные вложения – отправление не доставлено', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:24' => array( 'label' => 'Неудачная попытка вручения — Отказ в импорте – запрещенные вложения', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:25' => array( 'label' => 'Неудачная попытка вручения — Засыл отправления', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:26' => array( 'label' => 'Неудачная попытка вручения — За смертью получателя', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:27' => array( 'label' => 'Неудачная попытка вручения — Национальный праздник', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:28' => array( 'label' => 'Неудачная попытка вручения — Утрата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:29' => array( 'label' => 'Неудачная попытка вручения — По распоряжению адресата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:30' => array( 'label' => 'Неудачная попытка вручения — Несоответствие возраста получателя "18+"', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:31' => array( 'label' => 'Неудачная попытка вручения — Нарушение требований Маркетплейса (МП)', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'13:-' => array( 'label' => 'Регистрация отправки', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'14:1' => array( 'label' => 'Таможенное оформление — Выпущено таможней', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:2' => array( 'label' => 'Таможенное оформление — Возвращено таможней', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:3' => array( 'label' => 'Таможенное оформление — Осмотрено таможней', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:4' => array( 'label' => 'Таможенное оформление — Отказ в выпуске', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:5' => array( 'label' => 'Таможенное оформление — Направлено с таможенным уведомлением', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:6' => array( 'label' => 'Таможенное оформление — Направлено с обязательной уплатой таможенных платежей', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:7' => array( 'label' => 'Таможенное оформление — Требуется досмотр', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:8' => array( 'label' => 'Таможенное оформление — Выпуск приостановлен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:9' => array( 'label' => 'Таможенное оформление — Отказ в приеме на таможню', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:10' => array( 'label' => 'Таможенное оформление — Проведен осмотр с использованием ТСТК', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:11' => array( 'label' => 'Таможенное оформление — ТК в рамках СУР', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:12' => array( 'label' => 'Таможенное оформление — Досмотр завершен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:13' => array( 'label' => 'Таможенное оформление — Выпуск разрешен. Таможенные платежи уплачены', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:14' => array( 'label' => 'Таможенное оформление — Отказ в выпуске. Таможенные платежи не уплачены', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:15' => array( 'label' => 'Таможенное оформление — Таможенная декларация не прошла ФЛК', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:16' => array( 'label' => 'Таможенное оформление — Выпущено таможней. Средства зарезервированы', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:17' => array( 'label' => 'Таможенное оформление — Отказ в выпуске по решению должностного лица', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:18' => array( 'label' => 'Таможенное оформление — Требуется предъявление в ТО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:19' => array( 'label' => 'Таможенное оформление — Отказ в автоматическом выпуске', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:20' => array( 'label' => 'Таможенное оформление — Отказ в выпуске. Товары не предъявлены', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:21' => array( 'label' => 'Таможенное оформление — Требуются результаты осмотра', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:22' => array( 'label' => 'Таможенное оформление — Возврат разрешен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:23' => array( 'label' => 'Таможенное оформление — Отказ в выпуске возвращаемых товаров', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:24' => array( 'label' => 'Таможенное оформление — Требуется рентген-контроль', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:25' => array( 'label' => 'Таможенное оформление — В убытии отказано', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:26' => array( 'label' => 'Таможенное оформление — Убытие разрешено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'15:-' => array( 'label' => 'Передача на временное хранение', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'16:-' => array( 'label' => 'Уничтожение', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'17:-' => array( 'label' => 'Оформление в собственность', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'18:-' => array( 'label' => 'Регистрация утраты', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'19:-' => array( 'label' => 'Таможенные платежи поступили', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'20:-' => array( 'label' => 'Регистрация', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'21:1' => array( 'label' => 'Доставка — Доставлено в почтовый ящик', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'21:2' => array( 'label' => 'Доставка — Доставлено в руки адресату под роспись', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'21:3' => array( 'label' => 'Доставка — Доставлено администратору или секретарю под роспись', 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'22:1' => array( 'label' => 'Недоставка — Отсутствие п/я', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:2' => array( 'label' => 'Недоставка — Отсутствие улицы, дома, квартиры', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:3' => array( 'label' => 'Недоставка — Несоответствие индекса ОПС выдачи', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:4' => array( 'label' => 'Недоставка — Неверный адрес/адрес не существует', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:5' => array( 'label' => 'Недоставка — Отказ в получении', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:6' => array( 'label' => 'Недоставка — Нет доступа по адресу', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:7' => array( 'label' => 'Недоставка — Организация сменила адрес', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:8' => array( 'label' => 'Недоставка — Адресат выбыл', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:9' => array( 'label' => 'Недоставка — Отправление не поместилось в п/я', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'23:-' => array( 'label' => 'Поступление на временное хранение', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1' => array( 'label' => 'Продление срока выпуска таможней — Предъявить на ветеринарный контроль', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:2' => array( 'label' => 'Продление срока выпуска таможней — Предъявить на фитосанитарный контроль', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:3' => array( 'label' => 'Продление срока выпуска таможней — Отбор проб и образцов', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:4' => array( 'label' => 'Продление срока выпуска таможней — Прочее', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1019' => array( 'label' => 'Продление срока выпуска таможней — Запрещенные вложения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1020' => array( 'label' => 'Продление срока выпуска таможней — Имеются ограничения на импортируемые вложения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1050' => array( 'label' => 'Продление срока выпуска таможней — Счет отсутствует', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1051' => array( 'label' => 'Продление срока выпуска таможней — Счет некорректен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1052' => array( 'label' => 'Продление срока выпуска таможней — Сертификат отсутствует или некорректен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1053' => array( 'label' => 'Продление срока выпуска таможней — Сертификат некорректен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1054' => array( 'label' => 'Продление срока выпуска таможней — Таможенная декларация отсутствует или некорректна', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1055' => array( 'label' => 'Продление срока выпуска таможней — CN 22/23 некорректна', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1056' => array( 'label' => 'Продление срока выпуска таможней — Вложения с высокой стоимостью - требуется ТД', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1057' => array( 'label' => 'Продление срока выпуска таможней — Контакт с клиентом невозможен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1058' => array( 'label' => 'Продление срока выпуска таможней — Ожидается передача в таможенный орган', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1059' => array( 'label' => 'Продление срока выпуска таможней — Требуются данные НДС/Номер ввоза', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1060' => array( 'label' => 'Продление срока выпуска таможней — Требуется сертификат для возвращенных вложений', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1061' => array( 'label' => 'Продление срока выпуска таможней — Требуется форма перевода для банка', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1062' => array( 'label' => 'Продление срока выпуска таможней — Некомплектная поставка', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1063' => array( 'label' => 'Продление срока выпуска таможней — Передано в таможенный орган', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1064' => array( 'label' => 'Продление срока выпуска таможней — Задержано в таможенном органе без указания причины', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1065' => array( 'label' => 'Продление срока выпуска таможней — Ожидается подтверждение стоимости от получателя', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1070' => array( 'label' => 'Продление срока выпуска таможней — Имеются ограничения на экспортируемые вложения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1073' => array( 'label' => 'Продление срока выпуска таможней — Неполная или некорректная документация', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1099' => array( 'label' => 'Продление срока выпуска таможней — Прочее', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'25:-' => array( 'label' => 'Вскрытие', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'26:1' => array( 'label' => 'Отмена — Требование отправителя', 'status' => DeliveryStatus::CANCELLED, 'terminal' => false ),
		'26:2' => array( 'label' => 'Отмена — Ошибка оператора', 'status' => DeliveryStatus::CANCELLED, 'terminal' => false ),
		'27:-' => array( 'label' => 'Получена электронная регистрация', 'status' => DeliveryStatus::CREATED_IN_CARRIER, 'terminal' => false ),
		'28:-' => array( 'label' => 'Присвоение идентификатора', 'status' => DeliveryStatus::CREATED_IN_CARRIER, 'terminal' => false ),
		'29:-' => array( 'label' => 'Регистрация прохождения в ММПО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'30:-' => array( 'label' => 'Отправка SRM', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:1' => array( 'label' => 'Обработка перевозчиком — Транспорт прибыл', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:5' => array( 'label' => 'Обработка перевозчиком — Бронирование подтверждено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:6' => array( 'label' => 'Обработка перевозчиком — Включено в план погрузки', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:7' => array( 'label' => 'Обработка перевозчиком — Исключено из плана погрузки', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:14' => array( 'label' => 'Обработка перевозчиком — Транспортный участок завершен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:21' => array( 'label' => 'Обработка перевозчиком — Доставлено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:23' => array( 'label' => 'Обработка перевозчиком — Почта в месте назначения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:24' => array( 'label' => 'Обработка перевозчиком — Погружено на борт', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:31' => array( 'label' => 'Обработка перевозчиком — В пути', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:40' => array( 'label' => 'Обработка перевозчиком — Почта поступила на склад перевозчика', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:41' => array( 'label' => 'Обработка перевозчиком — Перегрузка', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:42' => array( 'label' => 'Обработка перевозчиком — Передано другому перевозчику', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:43' => array( 'label' => 'Обработка перевозчиком — Получено от другого перевозчика', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:48' => array( 'label' => 'Обработка перевозчиком — Погружено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:57' => array( 'label' => 'Обработка перевозчиком — Не погружено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:59' => array( 'label' => 'Обработка перевозчиком — Выгружено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:74' => array( 'label' => 'Обработка перевозчиком — Принято к перевозке', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:82' => array( 'label' => 'Обработка перевозчиком — Возвращено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'32:-' => array( 'label' => 'Поступление от АПО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'33:1' => array( 'label' => 'Международная обработка — Передано перевозчику', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'33:2' => array( 'label' => 'Международная обработка — Получено назначенным оператором', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'33:3' => array( 'label' => 'Международная обработка — Обработка назначенным оператором', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'34:-' => array( 'label' => 'Электронное уведомление доступно для скачивания', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'35:1' => array( 'label' => 'Отказ в курьерской доставке — Не подлежащий доставке вид почтового отправления', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:2' => array( 'label' => 'Отказ в курьерской доставке — Превышение предельного веса, подлежащее доставке', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:3' => array( 'label' => 'Отказ в курьерской доставке — Превышение габаритных размеров, подлежащее доставке', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:4' => array( 'label' => 'Отказ в курьерской доставке — Дефектное почтовое отправление', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:5' => array( 'label' => 'Отказ в курьерской доставке — Наличие Таможенного уведомления', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:6' => array( 'label' => 'Отказ в курьерской доставке — Отсутствие Соглашения об обмене почтовыми отправлениями с наложенным платежом', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:7' => array( 'label' => 'Отказ в курьерской доставке — Возвращенное почтовое отправление', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:8' => array( 'label' => 'Отказ в курьерской доставке — Превышение суммы наложенного платежа, подлежащей взиманию на дому', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:9' => array( 'label' => 'Отказ в курьерской доставке — Неверно оформленные бланки или их отсутствие', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'36:0' => array( 'label' => 'Уточнение вида оплаты доставки — Включена в тариф', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'36:1' => array( 'label' => 'Уточнение вида оплаты доставки — Платная', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'36:2' => array( 'label' => 'Уточнение вида оплаты доставки — Предоплаченная', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'37:-' => array( 'label' => 'Редактирование отправителем', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'38:4' => array( 'label' => 'Задержка для уточнений у отправителя — Неправильный/нечитаемый/неполный адрес', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'38:13' => array( 'label' => 'Задержка для уточнений у отправителя — По требованию отправителя', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'38:25' => array( 'label' => 'Задержка для уточнений у отправителя — Засыл отправления', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:1' => array( 'label' => 'Таможенное декларирование — Регистрация', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:2' => array( 'label' => 'Таможенное декларирование — Предварительное решение "выпуск разрешен"', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:3' => array( 'label' => 'Таможенное декларирование — Отказ в выпуске товаров. Требуется предъявление таможенному органу без осмотра', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:4' => array( 'label' => 'Таможенное декларирование — Отказ в выпуске товаров. Требуется предъявление таможенному органу с осмотром', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:5' => array( 'label' => 'Таможенное декларирование — Отказ в регистрации', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:6' => array( 'label' => 'Таможенное декларирование — Отказ в выпуске. Товары не предъявлены', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:7' => array( 'label' => 'Таможенное декларирование — Данные от торговой площадки получены', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:8' => array( 'label' => 'Таможенное декларирование — Выпуск разрешен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:9' => array( 'label' => 'Таможенное декларирование — Отказ в выпуске', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:10' => array( 'label' => 'Таможенное декларирование — МПО отозвано декларантом', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'40:1' => array( 'label' => 'Таможенный контроль — Платежи уплачены', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'40:2' => array( 'label' => 'Таможенный контроль — Уведомление о проведении контроля', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'40:3' => array( 'label' => 'Таможенный контроль — Отказ в выпуске по решению должностного лица', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:1' => array( 'label' => 'Обработка таможенных платежей — Сумма платежа удержана УО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:2' => array( 'label' => 'Обработка таможенных платежей — Сумма платежа списана ФТС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:3' => array( 'label' => 'Обработка таможенных платежей — Сумма платежа для удержания УО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:4' => array( 'label' => 'Обработка таможенных платежей — Сумма платежа удержана УО полностью', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:5' => array( 'label' => 'Обработка таможенных платежей — Сумма платежа рассчитана УО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:6' => array( 'label' => 'Обработка таможенных платежей — Сумма платежа удержана ФТС полностью', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'42:1' => array( 'label' => 'Вторая неудачная попытка вручения — Временное отсутствие адресата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:2' => array( 'label' => 'Вторая неудачная попытка вручения — Доставка отложена по просьбе адресата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:3' => array( 'label' => 'Вторая неудачная попытка вручения — Неполный адрес', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:4' => array( 'label' => 'Вторая неудачная попытка вручения — Неправильный/нечитаемый/неполный адрес', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:5' => array( 'label' => 'Вторая неудачная попытка вручения — Адресат выбыл', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:6' => array( 'label' => 'Вторая неудачная попытка вручения — Адресат отказался от отправления', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:7' => array( 'label' => 'Вторая неудачная попытка вручения — Форс-мажор/непредвиденные обстоятельства', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:8' => array( 'label' => 'Вторая неудачная попытка вручения — Иная', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:9' => array( 'label' => 'Вторая неудачная попытка вручения — Адресат заберет отправление сам', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:10' => array( 'label' => 'Вторая неудачная попытка вручения — Адресат не доступен', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:11' => array( 'label' => 'Вторая неудачная попытка вручения — Неудачная доставка', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:12' => array( 'label' => 'Вторая неудачная попытка вручения — Истек срок хранения в почтомате', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:13' => array( 'label' => 'Вторая неудачная попытка вручения — По требованию отправителя', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:14' => array( 'label' => 'Вторая неудачная попытка вручения — Отправление повреждено и/или без вложения', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:15' => array( 'label' => 'Вторая неудачная попытка вручения — В ожидании оплаты сбора', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:16' => array( 'label' => 'Вторая неудачная попытка вручения — Адресат переехал', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:17' => array( 'label' => 'Вторая неудачная попытка вручения — У адресата есть абонентский ящик', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:18' => array( 'label' => 'Вторая неудачная попытка вручения — Нет доставки на дом', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:19' => array( 'label' => 'Вторая неудачная попытка вручения — Не отвечает таможенным требованиям', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:20' => array( 'label' => 'Вторая неудачная попытка вручения — Неполные/недостаточные/неверные документы', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:21' => array( 'label' => 'Вторая неудачная попытка вручения — Невозможно связаться с клиентом', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:22' => array( 'label' => 'Вторая неудачная попытка вручения — Адресат бастует', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:23' => array( 'label' => 'Вторая неудачная попытка вручения — Запрещенные вложения – отправление не доставлено', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:24' => array( 'label' => 'Вторая неудачная попытка вручения — Отказ в импорте – запрещенные вложения', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:25' => array( 'label' => 'Вторая неудачная попытка вручения — Засыл отправления', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:26' => array( 'label' => 'Вторая неудачная попытка вручения — За смертью получателя', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:27' => array( 'label' => 'Вторая неудачная попытка вручения — Национальный праздник', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:28' => array( 'label' => 'Вторая неудачная попытка вручения — Утрата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:29' => array( 'label' => 'Вторая неудачная попытка вручения — По распоряжению адресата', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:30' => array( 'label' => 'Вторая неудачная попытка вручения — Несоответствие возраста получателя «18+»', 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'43:-' => array( 'label' => 'Вручение разрешено', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'44:1' => array( 'label' => 'Отказ в приеме — Нарушение применения тарифов', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:2' => array( 'label' => 'Отказ в приеме — Несоответствие фактической массы', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:3' => array( 'label' => 'Отказ в приеме — Несоответствие оформления', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:4' => array( 'label' => 'Отказ в приеме — Нечитаемый ШИ', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:5' => array( 'label' => 'Отказ в приеме — Повреждение упаковки', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:6' => array( 'label' => 'Отказ в приеме — Нарушение подлинности ГЗПО', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:7' => array( 'label' => 'Отказ в приеме — Штрих-код РПО был отсканирован ранее', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:8' => array( 'label' => 'Отказ в приеме — Ошибка в адресе', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:9' => array( 'label' => 'Отказ в приеме — Превышение габаритов', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:10' => array( 'label' => 'Отказ в приеме — Некорректный индекс отправителя', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:11' => array( 'label' => 'Отказ в приеме — Некорректный ЗОО', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:12' => array( 'label' => 'Отказ в приеме — Отсутствует отправление', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:13' => array( 'label' => 'Отказ в приеме — Несоответствие вложения', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:14' => array( 'label' => 'Отказ в приеме — Возврат по условиям договора', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:15' => array( 'label' => 'Отказ в приеме — Распоряжение ЭТП', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:16' => array( 'label' => 'Отказ в приеме — Превышена предельная масса', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:17' => array( 'label' => 'Отказ в приеме — Отказ от передачи отправления', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:18' => array( 'label' => 'Отказ в приеме — Неверно оформленные бланки или их отсутствие', 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'45:-' => array( 'label' => 'Отказ от отправки электронного уведомления получателем', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'46:-' => array( 'label' => 'Отмена присвоения идентификатора', 'status' => DeliveryStatus::CANCELLED, 'terminal' => false ),
		'47:-' => array( 'label' => 'Подтверждение возможности приема', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'48:-' => array( 'label' => 'Частичное вручение', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'49:1' => array( 'label' => 'Отказ в продлении срока хранения — Отправление уже вручено', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:2' => array( 'label' => 'Отказ в продлении срока хранения — Заявка на продление срока хранения получена повторно', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:3' => array( 'label' => 'Отказ в продлении срока хранения — Заявка на продление срока хранения подана позже, чем за 24 часа окончания нормативного срока хранения', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:4' => array( 'label' => 'Отказ в продлении срока хранения — Наличие дебиторской задолженности по корпоративному клиенту', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:5' => array( 'label' => 'Отказ в продлении срока хранения — Наличие запрета со стороны Компании дистанционной торговли (интернет-магазина) на продление срока хранения', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:6' => array( 'label' => 'Отказ в продлении срока хранения — ПВЗ закрыт', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'50:1' => array( 'label' => 'Неудачная доставка в АПС — АПС отсутствует', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:2' => array( 'label' => 'Неудачная доставка в АПС — АПС не работает', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:3' => array( 'label' => 'Неудачная доставка в АПС — К АПС нет доступа', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:4' => array( 'label' => 'Неудачная доставка в АПС — Курьер не успел', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:5' => array( 'label' => 'Неудачная доставка в АПС — Нет свободных ячеек в АПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:6' => array( 'label' => 'Неудачная доставка в АПС — Курьер не смог совершить закладку', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:7' => array( 'label' => 'Неудачная доставка в АПС — Размер открывшейся ячейки меньше размера отправления', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:8' => array( 'label' => 'Неудачная доставка в АПС — Ячейка не открывается, сломана', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:1' => array( 'label' => 'Неудачная доставка в ПВЗ — ПВЗ закрыт временно', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:2' => array( 'label' => 'Неудачная доставка в ПВЗ — ПВЗ закрыт постоянно', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:3' => array( 'label' => 'Неудачная доставка в ПВЗ — Отказ ПВЗ в приеме', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:4' => array( 'label' => 'Неудачная доставка в ПВЗ — Курьер не успел', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:5' => array( 'label' => 'Неудачная доставка в ПВЗ — Отправление отсутствует', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:6' => array( 'label' => 'Неудачная доставка в ПВЗ — Засыл', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:7' => array( 'label' => 'Неудачная доставка в ПВЗ — Дефектное отправление', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'52:-' => array( 'label' => 'Отказ в резервировании ячейки АПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'53:1' => array( 'label' => 'Бронирование интервала доставки — Назначен интервал доставки при поступлении в место вручения', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'53:2' => array( 'label' => 'Бронирование интервала доставки — Назначен интервал доставки при оформлении отправления интернет-магазином', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'53:3' => array( 'label' => 'Бронирование интервала доставки — Назначен интервал доставки адресатом', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'54:1' => array( 'label' => 'Изменение (перебронирование) интервала доставки — Перенос по согласованию с клиентом', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'54:2' => array( 'label' => 'Изменение (перебронирование) интервала доставки — Перенос по инициативе Почты России', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:1' => array( 'label' => 'Отказ от бронирования интервала доставки — Возврат отправителю', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:2' => array( 'label' => 'Отказ от бронирования интервала доставки — Самостоятельный забор', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:3' => array( 'label' => 'Отказ от бронирования интервала доставки — Техническая причина', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:4' => array( 'label' => 'Отказ от бронирования интервала доставки — Нарушен срок сдачи отправителем', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:5' => array( 'label' => 'Отказ от бронирования интервала доставки — Отмена заявки на доставку клиентом', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:6' => array( 'label' => 'Отказ от бронирования интервала доставки — Отправление не прибыло в место вручения', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'56:1' => array( 'label' => 'Возврат в адресное ОПС — Адресат оставил РПО в ячейке ААПС', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'56:2' => array( 'label' => 'Возврат в адресное ОПС — Изъятие РПО из почтомата (АПС) осуществляет сотрудник ОПС', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'56:3' => array( 'label' => 'Возврат в адресное ОПС — Почтальоном по истечении срока хранения', 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'57:-' => array( 'label' => 'Отказ закладки в АПС', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'58:-' => array( 'label' => 'Изменение способа вручения ММО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:1' => array( 'label' => 'Неудачное изъятие из АПС — Ячейка АПС пуста', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:2' => array( 'label' => 'Неудачное изъятие из АПС — Ячейка АПС не открылась', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:3' => array( 'label' => 'Неудачное изъятие из АПС — АПС не работает', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:4' => array( 'label' => 'Неудачное изъятие из АПС — К АПС нет доступа', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:5' => array( 'label' => 'Неудачное изъятие из АПС — Дефектное отправление', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'61:-' => array( 'label' => 'Передано ведомственному перевозчику', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'62:-' => array( 'label' => 'Возвращено клиенту', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'63:-' => array( 'label' => 'НП оплачен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'64:-' => array( 'label' => 'Выплата возмещения произведена', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'65:-' => array( 'label' => 'Отправление отсутствует в СЦ', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'66:-' => array( 'label' => 'Передано АПО', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'67:-' => array( 'label' => 'Вывоз разрешен', 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'68:1' => array( 'label' => 'Излишки — Выявлено при инвентаризации', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:1' => array( 'label' => 'Неудачный курьерский сбор — Курьер не успел', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:2' => array( 'label' => 'Неудачный курьерский сбор — Курьер не успел в течение срока хранения', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:3' => array( 'label' => 'Неудачный курьерский сбор — ПВЗ закрыт временно', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:4' => array( 'label' => 'Неудачный курьерский сбор — ПВЗ закрыт постоянно', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:5' => array( 'label' => 'Неудачный курьерский сбор — Отправление отсутствует', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:6' => array( 'label' => 'Неудачный курьерский сбор — Технические причины', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'70:-' => array( 'label' => 'Электронное уведомление аннулировано', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:1' => array( 'label' => 'Недостача — Отсутствие в ёмкости', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:2' => array( 'label' => 'Недостача — Отсутствие при инвентаризации', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:3' => array( 'label' => 'Недостача — При приеме с транспортного средства', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:4' => array( 'label' => 'Недостача — Отсутствие в наличии в объекте', 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
	);

	public function __construct(
		private SettingsRepository $settings
	) {
	}

	/** @return array<string,array{label:string,status:string,terminal:bool}> */
	public static function catalog(): array {
		return self::CATALOG;
	}

	/** @return array<string,string> */
	public static function status_labels(): array {
		$result = array();
		foreach ( self::CATALOG as $key => $row ) {
			$result[ $key ] = $row['label'];
		}

		return $result;
	}

	/** @return array<string,string> */
	public static function default_mapping(): array {
		$result = array();
		foreach ( self::CATALOG as $key => $row ) {
			$result[ $key ] = $row['status'];
		}

		return $result;
	}

	/** @return array<string,string> */
	public function mapping(): array {
		$stored = $this->settings->get_array( self::MAPPING_KEY, array() );

		return $this->sanitize_mapping( array_merge( self::default_mapping(), $stored ) );
	}

	/** @param array<string,mixed> $mapping */
	public function save_mapping( array $mapping ): void {
		$this->settings->set( self::MAPPING_KEY, $this->sanitize_mapping( $mapping ) );
	}

	/**
	 * @param array<string,mixed> $mapping
	 * @return array<string,string>
	 */
	public function sanitize_mapping( array $mapping ): array {
		$result = array();
		foreach ( self::CATALOG as $key => $row ) {
			$value = sanitize_key( (string) ( $mapping[ $key ] ?? '' ) );
			$result[ $key ] = DeliveryStatus::is_valid( $value ) ? $value : $row['status'];
		}

		return $result;
	}

	/**
	 * @param array<string,mixed> $record
	 * @return array<string,mixed>
	 */
	public function map_record( array $record ): array {
		$type_id = $this->normalize_id( (string) ( $record['operation_type_id'] ?? '' ) );
		$attr_id = $this->normalize_id( (string) ( $record['operation_attr_id'] ?? '' ) );
		$key = $type_id . ':' . $attr_id;
		$catalog_key = isset( self::CATALOG[ $key ] ) ? $key : $type_id . ':-';
		$catalog_row = self::CATALOG[ $catalog_key ] ?? null;
		$mapping = $this->mapping();
		$status = null !== $catalog_row
			? (string) ( $mapping[ $catalog_key ] ?? $catalog_row['status'] )
			: DeliveryStatus::UNKNOWN;
		$status = DeliveryStatus::is_valid( $status ) ? $status : DeliveryStatus::UNKNOWN;
		$type_name = trim( (string) ( $record['operation_type_name'] ?? '' ) );
		$attr_name = trim( (string) ( $record['operation_attr_name'] ?? '' ) );
		$title = $this->carrier_title( $type_name, $attr_name );

		return array(
			'universal_status_code' => $status,
			'universal_status_label' => DeliveryStatus::label( $status ),
			'carrier_status_title' => $title,
			'carrier_status_description' => $title,
			'carrier_operation_type_id' => $type_id,
			'carrier_operation_type_name' => $type_name,
			'carrier_operation_attr_id' => $attr_id,
			'carrier_operation_attr_name' => $attr_name,
			'carrier_operation_date' => (string) ( $record['oper_date'] ?? '' ),
			'carrier_operation_address' => (string) ( $record['operation_address'] ?? '' ),
			'carrier_operation_index' => (string) ( $record['operation_index'] ?? '' ),
			'carrier_status_is_terminal' => null !== $catalog_row && (bool) $catalog_row['terminal'],
		);
	}

	private function carrier_title( string $type_name, string $attr_name ): string {
		if ( '' !== $type_name && '' !== $attr_name ) {
			return $type_name . ' — ' . $attr_name;
		}

		return '' !== $type_name ? $type_name : $attr_name;
	}

	private function normalize_id( string $value ): string {
		$value = trim( $value );
		if ( is_numeric( $value ) ) {
			return (string) (int) $value;
		}

		return $value;
	}
}
