<?php
declare(strict_types=1);

namespace WallsShop\WDC\Shipments\RussianPost;

use WallsShop\WDC\Domain\Status\DeliveryStatus;

defined( 'ABSPATH' ) || exit;

final class RussianPostTrackingStatusMapper {
	/**
	 * Source of truth: status pocha.xlsx from the 0.36.0 Russian Post tracking task.
	 * Keys are operation_type_id:operation_attr_id.
	 *
	 * @var array<string,array{status:string,terminal:bool}>
	 */
	private const MAP = array(
		'1:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:9' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:10' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:11' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'1:12' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'2:1' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:2' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:3' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:4' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:5' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:6' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:7' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:8' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:9' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:10' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:11' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:12' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:13' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:14' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:15' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:16' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:17' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:18' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:19' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:20' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:21' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:22' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:23' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => true ),
		'2:24' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => true ),
		'2:25' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:26' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:27' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:28' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:29' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:30' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:31' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:32' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:33' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:34' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:35' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'2:36' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'2:37' => array( 'status' => DeliveryStatus::RETURNED_TO_SENDER, 'terminal' => false ),
		'3:1' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:2' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:3' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:4' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:5' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:6' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:7' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:8' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:9' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:10' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:11' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:12' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:13' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:14' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:15' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:16' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:17' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:18' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:19' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:20' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:21' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:22' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'3:23' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'4:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:9' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:10' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:11' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:12' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:13' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:14' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:15' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:16' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:17' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:18' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'4:19' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'5:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'5:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'5:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'5:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'5:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'5:9' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'6:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'7:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:0' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:2' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:9' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:10' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:11' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:12' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:13' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:14' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:15' => array( 'status' => DeliveryStatus::HANDED_TO_COURIER, 'terminal' => false ),
		'8:16' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:17' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:18' => array( 'status' => DeliveryStatus::HANDED_TO_COURIER, 'terminal' => false ),
		'8:19' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:20' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:21' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:22' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:23' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:24' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:25' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:26' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:27' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:28' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:29' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:30' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:31' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:32' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:33' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:34' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:35' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:36' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:37' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:38' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:39' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:40' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:41' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:42' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:43' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:44' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:45' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:46' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:47' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:48' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:49' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:50' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:51' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:52' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:53' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:54' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:55' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:56' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:57' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:58' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:59' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'8:60' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:61' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:62' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:63' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:64' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:65' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:66' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:67' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:68' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:69' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:70' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:71' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:72' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:73' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:74' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:75' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:76' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:77' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:78' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:79' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:80' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:81' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:82' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:83' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:84' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:85' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:86' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:87' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:88' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:89' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:90' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:91' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:92' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'8:93' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'9:1' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'9:2' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'10:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'11:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'12:1' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:2' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:3' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:4' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:5' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:6' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:7' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:8' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:9' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:10' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:11' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:12' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:13' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:14' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:15' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:16' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:17' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:18' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:19' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:20' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:21' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:22' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:23' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:24' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:25' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:26' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:27' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:28' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:29' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:30' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'12:31' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'13:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'14:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:9' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:10' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:11' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:12' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:13' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:14' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:15' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:16' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:17' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:18' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:19' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:20' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:21' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:22' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:23' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:24' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:25' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'14:26' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'15:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'16:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'17:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'18:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => true ),
		'19:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'20:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'21:1' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'21:2' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'21:3' => array( 'status' => DeliveryStatus::DELIVERED, 'terminal' => false ),
		'22:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'22:9' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'23:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1019' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1020' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1050' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1051' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1052' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1053' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1054' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1055' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1056' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1057' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1058' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1059' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1060' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1061' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1062' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1063' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1064' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1065' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1070' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1073' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'24:1099' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'25:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'26:1' => array( 'status' => DeliveryStatus::CANCELLED, 'terminal' => false ),
		'26:2' => array( 'status' => DeliveryStatus::CANCELLED, 'terminal' => false ),
		'27:-' => array( 'status' => DeliveryStatus::CREATED_IN_CARRIER, 'terminal' => false ),
		'28:-' => array( 'status' => DeliveryStatus::CREATED_IN_CARRIER, 'terminal' => false ),
		'29:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'30:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:14' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:21' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:23' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:24' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:31' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:40' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:41' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:42' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:43' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:48' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:57' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:59' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:74' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'31:82' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'32:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'33:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'33:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'33:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'34:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'35:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'35:9' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'36:0' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'36:1' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'36:2' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'37:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'38:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'38:13' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'38:25' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:9' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'39:10' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'40:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'40:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'40:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'41:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'42:1' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:2' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:3' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:4' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:5' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:6' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:7' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:8' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:9' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:10' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:11' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:12' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:13' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:14' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:15' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:16' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:17' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:18' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:19' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:20' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:21' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:22' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:23' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:24' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:25' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:26' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:27' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:28' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:29' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'42:30' => array( 'status' => DeliveryStatus::READY_FOR_PICKUP, 'terminal' => false ),
		'43:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'44:1' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:2' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:3' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:4' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:5' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:6' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:7' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:8' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:9' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:10' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:11' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:12' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:13' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:14' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:15' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:16' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:17' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'44:18' => array( 'status' => DeliveryStatus::REJECTED, 'terminal' => false ),
		'45:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'46:-' => array( 'status' => DeliveryStatus::CANCELLED, 'terminal' => false ),
		'47:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'48:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'49:1' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:2' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:3' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:4' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:5' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'49:6' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'50:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'50:8' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'51:7' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'52:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'53:1' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'53:2' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'53:3' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'54:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'54:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'55:6' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'56:1' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'56:2' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'56:3' => array( 'status' => DeliveryStatus::RETURNING_TO_SENDER, 'terminal' => false ),
		'57:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'58:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:1' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:2' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:3' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:4' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'60:5' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'61:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'62:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'63:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'64:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'65:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'66:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'67:-' => array( 'status' => DeliveryStatus::IN_TRANSIT, 'terminal' => false ),
		'68:1' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:1' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:2' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:3' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:4' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:5' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'69:6' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'70:-' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:1' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:2' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:3' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
		'1027:4' => array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false ),
	);

	/**
	 * @param array<string,string> $record
	 * @return array<string,mixed>
	 */
	public function map_record( array $record ): array {
		$type_id = $this->normalize_id( (string) ( $record['operation_type_id'] ?? '' ) );
		$attr_id = $this->normalize_id( (string) ( $record['operation_attr_id'] ?? '' ) );
		$key = $type_id . ':' . $attr_id;
		$mapped = self::MAP[ $key ] ?? self::MAP[ $type_id . ':-' ] ?? array( 'status' => DeliveryStatus::UNKNOWN, 'terminal' => false );
		$status = DeliveryStatus::is_valid( (string) $mapped['status'] ) ? (string) $mapped['status'] : DeliveryStatus::UNKNOWN;
		$type_name = trim( (string) ( $record['operation_type_name'] ?? '' ) );
		$attr_name = trim( (string) ( $record['operation_attr_name'] ?? '' ) );
		$title = $this->carrier_title( $type_name, $attr_name );

		return array(
			'universal_status_code' => $status,
			'universal_status_label' => DeliveryStatus::label( $status ),
			'carrier_status_title' => $title,
			'carrier_status_description' => $title,
			'carrier_operation_type_id' => $type_id,
			'carrier_operation_type_name' => $type_name,
			'carrier_operation_attr_id' => $attr_id,
			'carrier_operation_attr_name' => $attr_name,
			'carrier_operation_date' => (string) ( $record['oper_date'] ?? '' ),
			'carrier_operation_address' => (string) ( $record['operation_address'] ?? '' ),
			'carrier_operation_index' => (string) ( $record['operation_index'] ?? '' ),
			'carrier_status_is_terminal' => (bool) $mapped['terminal'],
		);
	}

	/**
	 * @return array<string,array{status:string,terminal:bool}>
	 */
	public function mapping(): array {
		return self::MAP;
	}

	private function carrier_title( string $type_name, string $attr_name ): string {
		if ( '' !== $type_name && '' !== $attr_name ) {
			return $type_name . ' — ' . $attr_name;
		}

		return '' !== $type_name ? $type_name : $attr_name;
	}

	private function normalize_id( string $value ): string {
		$value = trim( $value );
		if ( is_numeric( $value ) ) {
			return (string) (int) $value;
		}

		return $value;
	}
}
