<?php
declare(strict_types=1);
namespace WallsShop\WDC\Carriers\OzonDelivery\Admin;
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryConnectionDiagnosticService;
use WallsShop\WDC\Carriers\OzonDelivery\OzonDeliveryCredentials;
use WallsShop\WDC\Carriers\OzonDelivery\OzonDeliverySettings;
use WallsShop\WDC\Carriers\OzonDelivery\Pickup\OzonDeliveryPickupRepository;
use WallsShop\WDC\Carriers\OzonDelivery\Pickup\OzonDeliveryPickupScheduler;
defined( 'ABSPATH' ) || exit;
final class OzonDeliveryAdminPage {
	public const ACTIONS = array( 'save_ozon_delivery_settings', 'check_ozon_delivery_connection', 'save_ozon_delivery_pickup_schedule', 'start_ozon_delivery_pickup_import' );
	public function __construct( private OzonDeliveryCredentials $credentials, private OzonDeliverySettings $settings, private OzonDeliveryConnectionDiagnosticService $diagnostics, private ?OzonDeliveryPickupRepository $pickup_repository = null, private ?OzonDeliveryPickupScheduler $pickup_scheduler = null ) {}
	public static function supports_action( string $action ): bool { return in_array( $action, self::ACTIONS, true ); }
	/** @param array<string,mixed> $post */ public function handle_action( string $action, array $post ): void { if ( 'save_ozon_delivery_settings' === $action ) { $this->credentials->save_from_admin( $post ); } elseif ( 'check_ozon_delivery_connection' === $action ) { $this->diagnostics->run(); } elseif ( 'save_ozon_delivery_pickup_schedule' === $action ) { $this->settings->save_pickup_schedule( $post ); $this->pickup_scheduler?->reschedule(); } elseif ( 'start_ozon_delivery_pickup_import' === $action ) { $this->pickup_scheduler?->start_manual(); } }
	public function render(): void { $diagnostic = $this->settings->last_diagnostic(); ?>
		<h2><?php echo esc_html( OzonDeliverySettings::TITLE ); ?></h2>
		<h3><?php echo esc_html__( 'Подключение к API', 'walls-delivery-calc' ); ?></h3>
		<form method="post" style="max-width:760px;"><?php wp_nonce_field( 'wdc_delivery_services' ); ?><input type="hidden" name="wdc_delivery_services_action" value="save_ozon_delivery_settings"><table class="form-table" role="presentation"><tr><th><label for="ozon_delivery_client_id">Client ID</label></th><td><input class="regular-text" id="ozon_delivery_client_id" name="ozon_delivery_client_id" value="<?php echo esc_attr( $this->credentials->client_id() ); ?>"></td></tr><tr><th><label for="ozon_delivery_client_secret">Client Secret</label></th><td><input class="regular-text" type="password" id="ozon_delivery_client_secret" name="ozon_delivery_client_secret" value=""><p class="description"><?php echo esc_html( $this->credentials->has_client_secret() ? 'Client Secret сохранён' : 'Client Secret не сохранён' ); ?></p><label><input type="checkbox" name="ozon_delivery_clear_client_secret" value="1"> <?php echo esc_html__( 'Очистить Client Secret', 'walls-delivery-calc' ); ?></label><?php if ( ! $this->credentials->encryption_ready() ) : ?><p class="description">APP_ENCRYPTION_KEY не задан: новый Client Secret не будет сохранён.</p><?php endif; ?></td></tr></table><?php submit_button( __( 'Сохранить настройки', 'walls-delivery-calc' ) ); ?></form>
		<h3><?php echo esc_html__( 'Проверка подключения', 'walls-delivery-calc' ); ?></h3><form method="post"><?php wp_nonce_field( 'wdc_delivery_services' ); ?><input type="hidden" name="wdc_delivery_services_action" value="check_ozon_delivery_connection"><?php submit_button( __( 'Проверить подключение', 'walls-delivery-calc' ), 'secondary' ); ?></form>
		<?php if ( array() !== $diagnostic ) : ?><table class="widefat striped" style="max-width:760px;"><tbody><tr><th>Статус</th><td><?php echo esc_html( ! empty( $diagnostic['success'] ) ? 'Успешно' : 'Ошибка' ); ?></td></tr><tr><th>Проверено</th><td><?php echo esc_html( (string) ( $diagnostic['checked_at'] ?? '—' ) ); ?></td></tr><tr><th>Credentials</th><td><?php echo esc_html( ! empty( $diagnostic['credentials_present'] ) ? 'Заполнены' : 'Не заполнены' ); ?></td></tr><tr><th>OAuth token</th><td><?php echo esc_html( ! empty( $diagnostic['oauth_token_received'] ) ? 'Получен' : 'Не получен' ); ?></td></tr><tr><th>Прикладной API</th><td><?php echo esc_html( ! empty( $diagnostic['application_api_checked'] ) ? 'Проверен' : 'Не проверялся' ); ?></td></tr><tr><th>HTTP status</th><td><?php echo esc_html( (string) ( $diagnostic['http_status'] ?: '—' ) ); ?></td></tr><tr><th>Scope</th><td><?php echo esc_html( is_array( $diagnostic['token_scope'] ?? null ) && array() !== $diagnostic['token_scope'] ? implode( ', ', $diagnostic['token_scope'] ) : '—' ); ?></td></tr><tr><th>Тип token</th><td><?php echo esc_html( (string) ( $diagnostic['token_type'] ?: '—' ) ); ?></td></tr><tr><th>Срок действия известен</th><td><?php echo esc_html( ! empty( $diagnostic['token_expiry_known'] ) ? 'Да' : 'Нет' ); ?></td></tr><tr><th>Истекает</th><td><?php echo esc_html( (string) ( $diagnostic['token_expires_at'] ?: '—' ) ); ?></td></tr><tr><th>Источник token</th><td><?php echo esc_html( (string) ( $diagnostic['token_source'] ?: '—' ) ); ?></td></tr><tr><th>Код ошибки</th><td><?php echo esc_html( (string) ( $diagnostic['error_code'] ?: '—' ) ); ?></td></tr><tr><th>Операция</th><td><?php echo esc_html( (string) ( $diagnostic['operation'] ?? '—' ) ); ?></td></tr><tr><th>Content-Type</th><td><?php echo esc_html( (string) ( $diagnostic['response_content_type'] ?? '—' ) ); ?></td></tr><tr><th>Ответ JSON</th><td><?php echo esc_html( array_key_exists( 'response_json', $diagnostic ) ? ( $diagnostic['response_json'] ? 'Да' : 'Нет' ) : '—' ); ?></td></tr><tr><th>Структура ответа</th><td><?php echo esc_html( (string) ( $diagnostic['response_root'] ?? '—' ) ); ?></td></tr><tr><th>Поля ответа</th><td><?php echo esc_html( is_array( $diagnostic['response_keys'] ?? null ) && array() !== $diagnostic['response_keys'] ? implode( ', ', $diagnostic['response_keys'] ) : '—' ); ?></td></tr><tr><th>Размер ответа</th><td><?php echo esc_html( isset( $diagnostic['response_size_bytes'] ) ? (string) $diagnostic['response_size_bytes'] . ' байт' : '—' ); ?></td></tr><tr><th>Сообщение</th><td><?php echo esc_html( (string) ( $diagnostic['message'] ?? '' ) ); ?></td></tr></tbody></table><?php endif; ?>
		<h3><?php echo esc_html__( 'Подтверждённая схема передачи', 'walls-delivery-calc' ); ?></h3><p><strong><?php echo esc_html__( 'Самостоятельная сдача.', 'walls-delivery-calc' ); ?></strong></p><p><?php echo esc_html__( 'Забор курьером со склада отправителя не используется.', 'walls-delivery-calc' ); ?></p>
	<?php }
	public function render_pickup(): void { $active = $this->pickup_repository?->active_generation(); $count = $this->pickup_repository?->active_count() ?? 0; $next = $this->pickup_scheduler?->next_run(); ?>
		<h2><?php echo esc_html__( 'ПВЗ Ozon', 'walls-delivery-calc' ); ?></h2>
		<h3><?php echo esc_html__( 'Настройки', 'walls-delivery-calc' ); ?></h3><form method="post" style="max-width:760px"><?php wp_nonce_field( 'wdc_delivery_services' ); ?><input type="hidden" name="wdc_delivery_services_action" value="save_ozon_delivery_pickup_schedule"><table class="form-table" role="presentation"><tr><th>Автоматически обновлять ПВЗ</th><td><label><input type="checkbox" name="ozon_delivery_pickup_auto_sync" value="1" <?php checked( $this->settings->pickup_auto_sync_enabled() ); ?>> <?php echo esc_html__( 'Раз в сутки', 'walls-delivery-calc' ); ?></label></td></tr><tr><th><label for="ozon_delivery_pickup_sync_time">Время обновления</label></th><td><input id="ozon_delivery_pickup_sync_time" name="ozon_delivery_pickup_sync_time" value="<?php echo esc_attr( $this->settings->pickup_sync_time() ); ?>" pattern="[0-2][0-9]:[0-5][0-9]" maxlength="5"><p class="description">Часовой пояс сайта: <?php echo esc_html( wp_timezone_string() ?: 'UTC' ); ?>. Следующий запуск: <?php echo esc_html( $next ? wp_date( 'Y-m-d H:i', $next ) : '—' ); ?>.</p></td></tr></table><?php submit_button( __( 'Сохранить настройки', 'walls-delivery-calc' ) ); ?></form>
		<h3><?php echo esc_html__( 'Рабочий справочник', 'walls-delivery-calc' ); ?></h3><table class="widefat striped" style="max-width:760px"><tbody><tr><th>Активное поколение</th><td data-wdc-ozon-active-field="active_generation_id"><?php echo esc_html( $active['id'] ?? '—' ); ?></td></tr><tr><th>Активных ПВЗ</th><td data-wdc-ozon-active-field="active_count"><?php echo esc_html( (string) $count ); ?></td></tr><tr><th>Последний успешный импорт</th><td data-wdc-ozon-active-field="active_completed_at"><?php echo esc_html( $active['completed_at'] ?? '—' ); ?></td></tr><tr><th>Статус</th><td data-wdc-ozon-active-field="state"><?php echo esc_html( $active['state'] ?? 'Справочник ещё не загружен' ); ?></td></tr></tbody></table>
		<?php $status = $this->pickup_status(); ?><h3><?php echo esc_html__( 'Ход синхронизации', 'walls-delivery-calc' ); ?></h3><div data-wdc-ozon-pickup-progress data-wdc-ozon-state="<?php echo esc_attr( (string) $status['state'] ); ?>"><div class="notice inline" data-wdc-ozon-progress-bar hidden><p>Импорт выполняется...</p></div><table class="widefat striped" style="max-width:760px"><tbody><tr><th>Статус</th><td data-wdc-ozon-field="state"></td></tr><tr><th>Начало</th><td data-wdc-ozon-field="started_at"></td></tr><tr><th>Последнее обновление</th><td data-wdc-ozon-field="progress_updated_at"></td></tr><tr><th>Обработано страниц</th><td data-wdc-ozon-field="page_count"></td></tr><tr><th>Получено ID ПВЗ</th><td data-wdc-ozon-field="downloaded_count"></td></tr><tr><th>Сохранено ПВЗ</th><td data-wdc-ozon-field="accepted_count"></td></tr><tr><th>Отклонено</th><td data-wdc-ozon-field="rejected_count"></td></tr><tr><th>Дубликатов</th><td data-wdc-ozon-field="duplicate_count"></td></tr><tr><th>Конфликтов</th><td data-wdc-ozon-field="conflict_count"></td></tr><tr data-wdc-ozon-error-row hidden><th>Ошибка</th><td data-wdc-ozon-field="safe_error_message"></td></tr></tbody></table><p class="description" data-wdc-ozon-stall hidden></p></div>
		<h3><?php echo esc_html__( 'Синхронизация', 'walls-delivery-calc' ); ?></h3><form method="post"><?php wp_nonce_field( 'wdc_delivery_services' ); ?><input type="hidden" name="wdc_delivery_services_action" value="start_ozon_delivery_pickup_import"><?php submit_button( __( 'Обновить ПВЗ сейчас', 'walls-delivery-calc' ), 'secondary', 'submit', false, array( 'data-wdc-ozon-start' => '1', 'disabled' => ! empty( $status['is_running'] ) ) ); ?></form><p class="description" data-wdc-ozon-snapshot-message>Справочник публикуется только после полного успешного импорта. При ошибке используется предыдущий успешно загруженный справочник.</p>
	<?php }
	/** @return array<string,mixed> */ public function pickup_status(): array { return $this->pickup_repository?->status() ?? array( 'state' => 'idle', 'is_running' => false, 'is_terminal' => true, 'active_count' => 0 ); }
}
