<?php
declare(strict_types=1);
define( 'ABSPATH', __DIR__ );
define( 'APP_ENCRYPTION_KEY', 'ozon-delivery-smoke-key' );
define( 'WDC_PLUGIN_DIR', dirname( __DIR__, 2 ) . DIRECTORY_SEPARATOR );
function oz_assert( bool $ok, string $message ): void { if ( ! $ok ) { fwrite( STDERR, "[FAIL] {$message}\n" ); exit( 1 ); } }
function get_option( string $name, mixed $default = false ): mixed { return $GLOBALS['oz_options'][ $name ] ?? $default; }
function update_option( string $name, mixed $value, bool $autoload = true ): bool { $GLOBALS['oz_options'][ $name ] = $value; return true; }
function sanitize_text_field( string $value ): string { return trim( strip_tags( $value ) ); }
function wp_unslash( mixed $value ): mixed { return $value; }
function wp_json_encode( mixed $value, int $flags = 0, int $depth = 512 ): string|false { return json_encode( $value, $flags, $depth ); }
function get_transient( string $key ): mixed { return $GLOBALS['oz_transients'][ $key ] ?? false; }
function set_transient( string $key, mixed $value, int $expiration = 0 ): bool { $GLOBALS['oz_transients'][ $key ] = $value; return true; }
function delete_transient( string $key ): bool { unset( $GLOBALS['oz_transients'][ $key ] ); return true; }
require_once WDC_PLUGIN_DIR . 'src/Core/Autoloader.php'; ( new WallsShop\WDC\Core\Autoloader( 'WallsShop\\WDC\\', WDC_PLUGIN_DIR . 'src' ) )->register();
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryAccessTokenService;
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryApiException;
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryApiResponse;
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryConnectionDiagnosticService;
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryHttpClientInterface;
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryMessageSanitizer;
use WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryTokenCache;
use WallsShop\WDC\Carriers\OzonDelivery\OzonDeliveryCredentials;
use WallsShop\WDC\Carriers\OzonDelivery\OzonDeliverySettings;
use WallsShop\WDC\Infrastructure\Security\EncryptionService;
use WallsShop\WDC\Infrastructure\Settings\SettingsRepository;
final class OzFakeHttp implements OzonDeliveryHttpClientInterface { public array $requests = array(); /** @param array<int,OzonDeliveryApiResponse|\Throwable> $responses */ public function __construct( private array $responses ) {} public function request( string $method, string $url, array $args = array() ): OzonDeliveryApiResponse { $this->requests[] = compact( 'method', 'url', 'args' ); $response = array_shift( $this->responses ) ?? new OzonDeliveryApiResponse( 500, '' ); if ( $response instanceof \Throwable ) { throw $response; } return $response; } }
function oz_token_response( string $token, mixed $expires_in = null ): OzonDeliveryApiResponse { $body = array( 'access_token' => $token, 'refresh_token' => 'fake-refresh-token', 'scope' => array( 'delivery-api.all' ), 'token_type' => 'bearer' ); if ( null !== $expires_in ) { $body['expires_in'] = $expires_in; } return new OzonDeliveryApiResponse( 200, json_encode( $body ) ?: '{}' ); }
$GLOBALS['oz_options'] = array(); $GLOBALS['oz_transients'] = array(); $repo = new SettingsRepository(); $settings = new OzonDeliverySettings( $repo ); $encryption = new EncryptionService(); $cache = new OzonDeliveryTokenCache( $encryption ); $credentials = new OzonDeliveryCredentials( $repo, $encryption, $cache );
oz_assert( OzonDeliverySettings::CARRIER_KEY === 'ozon_delivery' && OzonDeliverySettings::SERVICE_KEY === 'ozon_delivery' && OzonDeliverySettings::TOKEN_SCOPE === array( 'delivery-api.all' ), 'stable keys and approved scope are required.' );
oz_assert( array_key_exists( OzonDeliverySettings::CLIENT_ID_KEY, $repo->defaults() ), 'SettingsRepository must compose Ozon defaults.' );
oz_assert( 30 === $settings->request_timeout(), 'Ozon HTTP timeout default must be 30 seconds.' );
$repo->set( OzonDeliverySettings::REQUEST_TIMEOUT_KEY, 15 ); oz_assert( 15 === $settings->request_timeout(), 'an explicitly stored Ozon timeout must be preserved.' );
$repo->set( OzonDeliverySettings::REQUEST_TIMEOUT_KEY, 99 ); oz_assert( 30 === $settings->request_timeout(), 'Ozon timeout upper bound must remain 30 seconds.' );
$repo->set( OzonDeliverySettings::REQUEST_TIMEOUT_KEY, 0 ); oz_assert( 1 === $settings->request_timeout(), 'Ozon timeout lower bound must remain 1 second.' );
oz_assert( $credentials->save_from_admin( array( OzonDeliverySettings::CLIENT_ID_KEY => ' client-id ', 'ozon_delivery_client_secret' => 'secret-value' ) ), 'encrypted credential save must succeed.' );
$stored = get_option( 'wdc_core_settings', array() ); oz_assert( ! str_contains( serialize( $stored ), 'secret-value' ) && $credentials->client_id() === 'client-id' && $credentials->client_secret() === 'secret-value', 'secret must be encrypted and client ID sanitized.' );
$before = $stored[ OzonDeliverySettings::CLIENT_SECRET_ENCRYPTED_KEY ]; $credentials->save_from_admin( array( OzonDeliverySettings::CLIENT_ID_KEY => 'client-id' ) ); oz_assert( $before === get_option( 'wdc_core_settings', array() )[ OzonDeliverySettings::CLIENT_SECRET_ENCRYPTED_KEY ], 'blank secret must preserve stored secret.' );
$future = time() + 3600; $http = new OzFakeHttp( array( oz_token_response( 'fake-access-token', (string) $future ), oz_token_response( 'fresh-token-response', (string) $future ) ) ); $tokens = new OzonDeliveryAccessTokenService( $credentials, $http, new OzonDeliveryMessageSanitizer(), $cache );
oz_assert( $tokens->get_token() === 'fake-access-token' && $tokens->get_token() === 'fake-access-token' && 1 === count( $http->requests ), 'future-expiry token must be reused from cache without a second HTTP request.' );
$request = $http->requests[0]; $body = json_decode( $request['args']['body'], true ); oz_assert( $request['method'] === 'POST' && $request['url'] === OzonDeliverySettings::TOKEN_URL && $request['args']['headers']['Content-Type'] === 'application/json' && $body['grant_type'] === 'client_credentials' && $body['scope'] === array( 'delivery-api.all' ), 'token request must match approved client_credentials contract.' );
oz_assert( ! str_contains( serialize( $GLOBALS['oz_transients'] ), 'fake-access-token' ) && ! str_contains( serialize( $GLOBALS['oz_transients'] ), 'fake-refresh-token' ), 'cache must store only encrypted access token and never refresh token.' );
$fresh = $tokens->obtain_fresh(); oz_assert( $fresh->expires_at === $future && $fresh->scope === array( 'delivery-api.all' ) && $fresh->token_type === 'bearer', 'live token response must normalize absolute expiry, scope, and type.' );
foreach ( array( time() + 60, time() - 1, 'invalid', null ) as $expires_in ) { $uncached = new OzonDeliveryAccessTokenService( $credentials, new OzFakeHttp( array( oz_token_response( 'uncached-' . md5( serialize( $expires_in ) ), $expires_in ) ) ), new OzonDeliveryMessageSanitizer(), new OzonDeliveryTokenCache( $encryption ) ); $token = $uncached->obtain_fresh(); oz_assert( (int) $expires_in > time() ? $token->expires_at === (int) $expires_in : null === $token->expires_at, 'absolute expiry must be preserved and malformed or missing values must remain unknown.' ); oz_assert( null === $cache->get( $credentials->account_fingerprint() ), 'expiry at the 60-second margin, past, malformed, or absent must not remain cached.' ); }
$old_fingerprint = $credentials->account_fingerprint(); $credentials->save_from_admin( array( OzonDeliverySettings::CLIENT_ID_KEY => 'client-id-2' ) ); oz_assert( $old_fingerprint !== $credentials->account_fingerprint() && array() === $GLOBALS['oz_transients'], 'Client ID change must invalidate the old token cache.' );
$change_http = new OzFakeHttp( array( oz_token_response( 'after-client-change', time() + 3600 ), oz_token_response( 'after-secret-change', time() + 3600 ) ) ); $changed_tokens = new OzonDeliveryAccessTokenService( $credentials, $change_http, new OzonDeliveryMessageSanitizer(), $cache ); oz_assert( $changed_tokens->get_token() === 'after-client-change', 'changed Client ID must not reuse old token.' ); $credentials->save_from_admin( array( OzonDeliverySettings::CLIENT_ID_KEY => 'client-id-2', 'ozon_delivery_client_secret' => 'secret-value-2' ) ); oz_assert( $changed_tokens->get_token() === 'after-secret-change' && 2 === count( $change_http->requests ), 'changed Client Secret must invalidate token cache.' ); $credentials->save_from_admin( array( OzonDeliverySettings::CLIENT_ID_KEY => 'client-id-2', 'ozon_delivery_clear_client_secret' => '1' ) ); oz_assert( array() === $GLOBALS['oz_transients'] && ! $credentials->has_client_secret(), 'explicit clear must remove the token cache and Client Secret.' );
$credentials->save_from_admin( array( OzonDeliverySettings::CLIENT_ID_KEY => 'client-id', 'ozon_delivery_client_secret' => 'secret-value' ) ); $diagnostic_http = new OzFakeHttp( array( oz_token_response( 'cached-before-diagnostic', time() + 3600 ), oz_token_response( 'fresh-diagnostic-token', time() + 3600 ) ) ); $diagnostic_tokens = new OzonDeliveryAccessTokenService( $credentials, $diagnostic_http, new OzonDeliveryMessageSanitizer(), $cache ); $diagnostic_tokens->get_token(); $diagnostic = new OzonDeliveryConnectionDiagnosticService( $credentials, $diagnostic_tokens, $settings ); $result = $diagnostic->run(); oz_assert( $result['success'] && $result['oauth_token_received'] && ! $result['application_api_checked'] && $result['token_scope'] === array( 'delivery-api.all' ) && $result['token_type'] === 'bearer' && $result['token_expiry_known'] && $result['token_source'] === 'fresh' && 2 === count( $diagnostic_http->requests ) && ! str_contains( serialize( $result ), 'fresh-diagnostic-token' ) && ! str_contains( serialize( $result ), 'fake-refresh-token' ), 'diagnostic must force fresh OAuth and expose only safe token metadata.' );
$html_response = new OzonDeliveryApiResponse( 403, '<html>secret-value fake-access-token</html>', array( 'content-type' => 'text/html; charset=utf-8' ) ); try { ( new OzonDeliveryAccessTokenService( $credentials, new OzFakeHttp( array( $html_response ) ), new OzonDeliveryMessageSanitizer(), $cache ) )->obtain_fresh(); oz_assert( false, 'HTML OAuth failure must fail.' ); } catch ( OzonDeliveryApiException $e ) { oz_assert( 403 === $e->http_status && 'oauth_token' === $e->operation && 'text/html' === $e->metadata['response_content_type'] && false === $e->metadata['response_json'] && ! str_contains( serialize( $e->metadata ), 'secret-value' ), 'OAuth evidence must retain only safe structural metadata.' ); }
$GLOBALS['oz_transients'] = array();
$endpoint_http = new OzFakeHttp( array( oz_token_response( 'endpoint-token', time() + 3600 ), new OzonDeliveryApiException( 'http', 'transport_error', 0, true, 'Ошибка соединения с Ozon Delivery.', array( 'safe_key' => 'safe-value' ) ), new OzonDeliveryApiException( 'http', 'transport_error', 0, true, 'Ошибка соединения с Ozon Delivery.' ), new OzonDeliveryApiException( 'http', 'redirect_limit', 302, true, 'Превышен лимит redirect Ozon Delivery.' ), new OzonDeliveryApiException( 'http', 'redirect_rejected', 302, false, 'Ozon Delivery вернул недопустимый redirect.' ) ) );
$endpoint_api = new WallsShop\WDC\Carriers\OzonDelivery\Api\OzonDeliveryApiClient( $endpoint_http, new OzonDeliveryAccessTokenService( $credentials, $endpoint_http, new OzonDeliveryMessageSanitizer(), $cache ) );
try { $endpoint_api->pickup_list(); oz_assert( false, 'pickup_list transport error accepted' ); } catch ( OzonDeliveryApiException $e ) { oz_assert( 'v1/delivery-point/list' === $e->operation && 'transport_error' === $e->safe_code && 0 === $e->http_status && true === $e->retryable && ( $e->metadata['safe_key'] ?? '' ) === 'safe-value', 'pickup_list transport error must be wrapped with endpoint operation while preserving safe fields.' ); }
try { $endpoint_api->pickup_info( array( 10 ) ); oz_assert( false, 'pickup_info transport error accepted' ); } catch ( OzonDeliveryApiException $e ) { oz_assert( 'v1/delivery-point/info' === $e->operation && 'transport_error' === $e->safe_code && true === $e->retryable, 'pickup_info transport error must be wrapped with endpoint operation.' ); }
try { $endpoint_api->pickup_list(); oz_assert( false, 'pickup_list redirect limit accepted' ); } catch ( OzonDeliveryApiException $e ) { oz_assert( 'v1/delivery-point/list' === $e->operation && 'redirect_limit' === $e->safe_code && 302 === $e->http_status && true === $e->retryable, 'pickup_list redirect_limit must be endpoint-aware and retryable.' ); }
try { $endpoint_api->pickup_list(); oz_assert( false, 'pickup_list unsafe redirect accepted' ); } catch ( OzonDeliveryApiException $e ) { oz_assert( 'v1/delivery-point/list' === $e->operation && 'redirect_rejected' === $e->safe_code && false === $e->retryable, 'pickup_list unsafe redirect must be endpoint-aware but permanent.' ); }
$safe = ( new OzonDeliveryMessageSanitizer() )->sanitize( 'Bearer fake-access-token client_secret=secret-value phone +79990001122 x@y.test' ); oz_assert( ! str_contains( $safe, 'fake-access-token' ) && ! str_contains( $safe, 'secret-value' ) && ! str_contains( $safe, '79990001122' ) && ! str_contains( $safe, 'x@y.test' ), 'sanitizer must redact secrets and personal data.' );
echo "Ozon Delivery foundation smoke passed.\n";
