<?php
declare(strict_types=1);
define( 'ABSPATH', __DIR__ );
function oau_assert( bool $ok, string $message ): void { if ( ! $ok ) { fwrite( STDERR, "[FAIL] {$message}\n" ); exit( 1 ); } }
$root = dirname( __DIR__, 2 ); $admin = file_get_contents( $root . '/src/Carriers/OzonDelivery/Admin/OzonDeliveryAdminPage.php' ) ?: ''; $routing = file_get_contents( $root . '/src/DeliveryServices/Admin/DeliveryServicesAdminPage.php' ) ?: ''; $repository = file_get_contents( $root . '/src/DeliveryServices/DeliveryServiceRepository.php' ) ?: ''; $manager = file_get_contents( $root . '/src/DeliveryServices/DeliveryServiceManager.php' ) ?: ''; $plugin = file_get_contents( $root . '/src/Core/Plugin.php' ) ?: '';
oau_assert( str_contains( $repository, 'ensure_ozon_delivery_service' ) && str_contains( $repository, 'OzonDeliverySettings::SERVICE_KEY' ) && str_contains( $manager, 'ozon_delivery_service_exists' ) && str_contains( $manager, "array( 'RU' )" ), 'Ozon must be an idempotent builtin DeliveryService with RU initial country.' );
oau_assert( str_contains( $routing, "'main' => 'Основное'" ) && str_contains( $routing, "'calculation' => 'Расчет'" ) && str_contains( $routing, "'rules' => 'Правила'" ) && str_contains( $routing, "\$tabs['ozon_api'] = 'API Ozon'" ) && str_contains( $routing, "\$tabs['ozon_statuses'] = 'Статусы Ozon'" ) && str_contains( $routing, 'render_ozon_api_tab' ) && str_contains( $routing, 'render_ozon_statuses_tab' ), 'Ozon must use generic service tabs with API, pickup and status mapping tabs.' );
oau_assert( ! str_contains( $routing, 'class="button" href="<?php echo esc_url( admin_url( \'admin.php?page=\' . self::MENU_SLUG . \'&service=\' . OzonDeliverySettings::SERVICE_KEY ) ); ?>"' ), 'standalone Ozon shortcut must not render before the service table.' );
oau_assert( str_contains( $admin, 'Client Secret сохранён' ) && ! str_contains( $admin, 'value="<?php echo esc_attr( $this->credentials->client_secret()' ), 'secret must never render in HTML.' );
oau_assert( str_contains( $admin, 'Самостоятельная сдача.' ) && str_contains( $admin, 'Забор курьером со склада отправителя не используется.' ), 'self-drop-off invariant must be visible.' );
oau_assert( str_contains( $admin, 'Резервный телефон для расчёта' ) && str_contains( $admin, 'Используется только если телефон покупателя отсутствует или не может быть приведён к корректному российскому формату.' ) && str_contains( $admin, 'type="tel"' ), 'Ozon admin pricing settings must expose the Russian fallback phone as an optional carrier-owned setting.' );
oau_assert( str_contains( $admin, 'Стоимость доставки' ) && str_contains( $admin, 'Страховка' ) && str_contains( $admin, 'Итого' ), 'Ozon admin quote diagnostic must expose delivery, insurance and total pricing rows.' );
oau_assert( str_contains( $admin, 'function render_statuses' ) && str_contains( $admin, 'documented_statuses()' ) && str_contains( $admin, 'Сопоставление статусов Ozon Delivery' ) && str_contains( $admin, 'Статус Ozon' ) && str_contains( $admin, 'Универсальный статус' ) && str_contains( $admin, '<select name="<?php echo esc_attr( OzonDeliverySettings::SHIPMENT_STATUS_MAPPING_KEY' ) && str_contains( $admin, 'Сохранить соответствия' ) && ! str_contains( $admin, 'Доступное действие' ), 'Ozon status admin tab must render editable dropdown mapping from the production status mapper and remove the action column.' );
oau_assert( str_contains( $admin, 'DeliveryStatus::all()' ) && str_contains( $admin, 'DeliveryStatus::label( $universal )' ) && str_contains( $admin, 'save_ozon_delivery_shipment_status_mapping' ), 'Ozon status admin tab must validate against universal DeliveryStatus values and save via carrier-owned action.' );
oau_assert( str_contains( $admin, 'function tab_for_action' ) && str_contains( $admin, "'save_ozon_delivery_settings', 'check_ozon_delivery_connection', 'check_ozon_delivery_quote' => 'ozon_api'" ) && str_contains( $admin, "'save_ozon_delivery_pickup_schedule', 'start_ozon_delivery_pickup_import' => 'ozon_pickup'" ) && str_contains( $admin, "'save_ozon_delivery_shipment_status_mapping' => 'ozon_statuses'" ) && str_contains( $routing, 'OzonDeliveryAdminPage::tab_for_action( $action )' ), 'Ozon admin actions must redirect to their explicit tabs, including ozon_statuses after status mapping save.' );
oau_assert( str_contains( $plugin, 'OzonDeliveryShipmentStatusMapper::class' ), 'Ozon runtime/admin must wire configurable status mapper through DI.' );
oau_assert( ! str_contains( $admin, 'Redirect URI' ) && ! str_contains( $admin, 'callback' ) && ! str_contains( $admin, 'Подключить Ozon' ), 'client_credentials admin UI must have no redirect/callback controls.' );
oau_assert( str_contains( $admin, 'HTTP status' ) && str_contains( $admin, 'Scope' ) && str_contains( $admin, 'Тип token' ) && str_contains( $admin, 'Срок действия известен' ) && str_contains( $admin, 'Истекает' ) && str_contains( $admin, 'Источник token' ) && ! str_contains( $admin, 'refresh_token' ), 'admin diagnostic must render only safe OAuth token metadata.' );
oau_assert( str_contains( $plugin, 'OzonDeliveryQuoteDiagnosticService::class' ) && str_contains( $plugin, 'OzonDeliveryCarrier::class' ) && str_contains( $plugin, 'OzonDeliveryShipmentAdapter::class' ) && str_contains( $plugin, 'OzonDeliveryShipmentDocumentProvider::class' ), 'Ozon admin/runtime must wire quote diagnostic, checkout carrier and Shipment Framework runtime.' );
echo "Ozon Delivery admin smoke passed.\n";
