<?php
declare(strict_types=1);
define( 'ABSPATH', dirname( __DIR__, 2 ) . '/' );
require_once dirname( __DIR__, 2 ) . '/src/Carriers/OzonDelivery/Pickup/OzonDeliveryPickupScheduleFormatter.php';
use WallsShop\WDC\Carriers\OzonDelivery\Pickup\OzonDeliveryPickupScheduleFormatter;
function oz_schedule_assert( bool $condition, string $message ): void { if ( ! $condition ) { throw new RuntimeException( $message ); } }
/** @param callable(int):array<int,array{0:string,1:string}> $periods @return array<int,array<string,mixed>> */
function oz_schedule_calendar( callable $periods, int $days = 21 ): array { $start = new DateTimeImmutable( '2026-08-24' ); $schedule = array(); for ( $offset = 0; $offset < $days; ++$offset ) { $date = $start->modify( '+' . $offset . ' days' ); $items = array(); foreach ( $periods( (int) $date->format( 'N' ) ) as $period ) { $items[] = array( 'from_local' => $period[0], 'to_local' => $period[1] ); } $schedule[] = array( 'date' => $date->format( 'Y-m-d' ), 'periods' => $items ); } return $schedule; }
$formatter = new OzonDeliveryPickupScheduleFormatter();
$daily = oz_schedule_calendar( static fn( int $day ): array => array( array( '09:00:00', '21:00:00' ) ) ); oz_schedule_assert( 'Ежедневно 09:00–21:00' === $formatter->format( $daily ), 'a stable 21-day daily schedule must be compressed.' );
$weekday_weekend = oz_schedule_calendar( static fn( int $day ): array => $day <= 5 ? array( array( '09:00:00', '21:00:00' ) ) : array( array( '10:00:00', '20:00:00' ) ) ); oz_schedule_assert( "Пн–Пт 09:00–21:00\nСб–Вс 10:00–20:00" === $formatter->format( $weekday_weekend ), 'weekday and weekend schedules must be grouped compactly.' );
$sunday_closed = oz_schedule_calendar( static fn( int $day ): array => 7 === $day ? array() : array( array( '09:00:00', '21:00:00' ) ) ); oz_schedule_assert( "Пн–Сб 09:00–21:00\nВс — выходной" === $formatter->format( $sunday_closed ), 'closed days must be represented without raw calendar data.' );
$split = oz_schedule_calendar( static fn( int $day ): array => array( array( '14:00:00', '21:00:00' ), array( '09:00:00', '13:00:00' ) ) ); oz_schedule_assert( 'Ежедневно 09:00–13:00, 14:00–21:00' === $formatter->format( $split ), 'multiple periods must be ordered and seconds must be stripped.' );
$invalid_date = $daily; $invalid_date[0]['date'] = '2026-02-30'; oz_schedule_assert( 'График работы уточняйте в пункте выдачи' === $formatter->format( $invalid_date ), 'invalid dates must use the safe fallback.' );
$invalid_time = $daily; $invalid_time[0]['periods'][0]['from_local'] = '9:00:00'; oz_schedule_assert( 'График работы уточняйте в пункте выдачи' === $formatter->format( $invalid_time ), 'invalid times must use the safe fallback.' );
$missing_periods = $daily; unset( $missing_periods[0]['periods'] ); oz_schedule_assert( 'График работы уточняйте в пункте выдачи' === $formatter->format( $missing_periods ), 'missing periods must use the safe fallback.' );
oz_schedule_assert( 'График работы уточняйте в пункте выдачи' === $formatter->format( oz_schedule_calendar( static fn( int $day ): array => array( array( '09:00:00', '21:00:00' ) ), 7 ) ), 'a short horizon must not claim a weekly rule.' );
$inconsistent = $daily; $inconsistent[14]['periods'][0] = array( 'from_local' => '10:00:00', 'to_local' => '18:00:00' ); oz_schedule_assert( 'График работы уточняйте в пункте выдачи' === $formatter->format( $inconsistent ), 'inconsistent weekdays must not claim a regular schedule.' );
$reversed = array_reverse( $weekday_weekend ); oz_schedule_assert( $formatter->format( $weekday_weekend ) === $formatter->format( $reversed ) && ! str_contains( $formatter->format( $weekday_weekend ), '2026-' ), 'schedule formatting must be deterministic and must not retain raw dates.' );
$too_many_periods = oz_schedule_calendar( static fn( int $day ): array => array_fill( 0, 100, array( '09:00:00', '21:00:00' ) ) ); oz_schedule_assert( 'Ежедневно 09:00–21:00' === $formatter->format( $too_many_periods ), 'duplicate periods must not expand stored schedule output.' );
$many_unique_periods = array(); for ( $period = 0; $period < 80; ++$period ) { $many_unique_periods[] = array( str_pad( (string) intdiv( $period, 4 ), 2, '0', STR_PAD_LEFT ) . ':' . str_pad( (string) ( $period % 4 * 15 ), 2, '0', STR_PAD_LEFT ) . ':00', '23:59:59' ); } $bounded = oz_schedule_calendar( static fn( int $day ): array => $many_unique_periods ); oz_schedule_assert( 'График работы уточняйте в пункте выдачи' === $formatter->format( $bounded ), 'stored schedule output must remain bounded.' );
echo "Ozon Delivery pickup schedule smoke passed.\n";
