<?php
declare(strict_types=1);
namespace WallsShop\WDC\Carriers\OzonDelivery\Pickup;
defined( 'ABSPATH' ) || exit;
final class OzonDeliveryPickupParser {
	/** @return array{ids:array<int,int>,next_cursor:?string} */ public function list_page( array $data ): array { $points = $data['delivery_points'] ?? null; if ( ! is_array( $points ) || array_is_list( $data ) ) { throw new \RuntimeException( 'pickup_list_invalid' ); } $ids = array(); foreach ( $points as $point ) { $id = is_array( $point ) ? (int) ( $point['delivery_point_id'] ?? 0 ) : 0; if ( $id <= 0 || isset( $ids[$id] ) ) { throw new \RuntimeException( 'pickup_list_identity_invalid' ); } $ids[$id] = $id; } $cursor = $data['next_cursor'] ?? null; if ( null !== $cursor && ( ! is_string( $cursor ) || '' === trim( $cursor ) ) ) { throw new \RuntimeException( 'pickup_cursor_invalid' ); } return array( 'ids' => array_values( $ids ), 'next_cursor' => $cursor ); }
	/** @return array<int,array<string,mixed>> */ public function info_page( array $data ): array { $points = $data['delivery_points'] ?? null; if ( ! is_array( $points ) || array_is_list( $data ) ) { throw new \RuntimeException( 'pickup_info_invalid' ); } $result = array(); foreach ( $points as $point ) { if ( is_array( $point ) ) { $normalized = $this->point( $point ); if ( null !== $normalized ) { $result[] = $normalized; } } } return $result; }
	/** @return array<string,mixed>|null */ private function point( array $point ): ?array { $id = (int) ( $point['delivery_point_id'] ?? 0 ); $name = $this->text( $point['name'] ?? '', 255 ); $address = $this->text( $point['full_address'] ?? '', 2000 ); $type = $this->text( $point['type'] ?? '', 32 ); if ( $id <= 0 || '' === $name || '' === $address || ! in_array( $type, array( 'unknown', 'pvz', 'postamat' ), true ) || ! is_array( $point['schedule'] ?? null ) || ! is_bool( $point['is_active'] ?? null ) || ! is_bool( $point['is_bulky'] ?? null ) ) { return null; } $coordinates = is_array( $point['coordinates'] ?? null ) ? $point['coordinates'] : array(); $lat = $this->number( $coordinates['latitude'] ?? null, -90, 90 ); $lng = $this->number( $coordinates['longitude'] ?? null, -180, 180 ); if ( ( null === $lat ) !== ( null === $lng ) ) { return null; } $restrictions = is_array( $point['restrictions'] ?? null ) ? $point['restrictions'] : array(); $schedule = wp_json_encode( $point['schedule'] ); if ( ! is_string( $schedule ) ) { return null; } $row = array( 'point_id' => $id, 'name' => $name, 'point_number' => $this->text( $point['delivery_point_number'] ?? '', 100 ), 'type' => $type, 'full_address' => $address, 'latitude' => $lat, 'longitude' => $lng, 'schedule_json' => $schedule, 'is_active' => (int) $point['is_active'], 'is_bulky' => (int) $point['is_bulky'], 'storage_period_days' => $this->integer( $point['storage_period_days'] ?? null ), 'fitting_rooms_count' => $this->integer( $point['fitting_rooms_count'] ?? null ), 'min_weight_g' => $this->integer( $restrictions['min_weight_g'] ?? null ), 'max_weight_g' => $this->integer( $restrictions['max_weight_g'] ?? null ), 'max_width_mm' => $this->integer( $restrictions['max_width_mm'] ?? null ), 'max_length_mm' => $this->integer( $restrictions['max_length_mm'] ?? null ), 'max_height_mm' => $this->integer( $restrictions['max_height_mm'] ?? null ) ); $row['fingerprint'] = hash( 'sha256', wp_json_encode( $row ) ?: '' ); return $row; }
	private function text( mixed $value, int $length ): string { return is_string( $value ) ? substr( trim( $value ), 0, $length ) : ''; }
	private function integer( mixed $value ): ?int { return is_int( $value ) || is_string( $value ) && preg_match( '/^-?\d+$/', $value ) ? (int) $value : null; }
	private function number( mixed $value, float $min, float $max ): ?float { if ( ! is_int( $value ) && ! is_float( $value ) && ! is_string( $value ) ) { return null; } $number = (float) $value; return is_finite( $number ) && $number >= $min && $number <= $max ? $number : null; }
}
