<?php
declare(strict_types=1);
namespace WallsShop\WDC\Carriers\OzonDelivery\Pickup;
defined( 'ABSPATH' ) || exit;
final class OzonDeliveryPickupRepository {
	private object $wpdb;
	public function __construct( ?object $wpdb = null ) { if ( null === $wpdb ) { global $wpdb; } $this->wpdb = $wpdb; }
	public function generations_table(): string { return $this->wpdb->prefix . 'wdc_ozon_delivery_pickup_generations'; }
	public function points_table(): string { return $this->wpdb->prefix . 'wdc_ozon_delivery_pickup_points'; }
	public function create_schema(): void { require_once ABSPATH . 'wp-admin/includes/upgrade.php'; $charset = $this->wpdb->get_charset_collate(); dbDelta( "CREATE TABLE {$this->generations_table()} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,state varchar(16) NOT NULL,job_id char(64) NOT NULL,started_at datetime NULL,completed_at datetime NULL,cursor_value varchar(255) NULL,page_count int unsigned NOT NULL DEFAULT 0,downloaded_count int unsigned NOT NULL DEFAULT 0,accepted_count int unsigned NOT NULL DEFAULT 0,rejected_count int unsigned NOT NULL DEFAULT 0,duplicate_count int unsigned NOT NULL DEFAULT 0,conflict_count int unsigned NOT NULL DEFAULT 0,safe_error_code varchar(80) NULL,safe_error_message varchar(300) NULL,PRIMARY KEY(id),UNIQUE KEY job_id(job_id),KEY state(state),KEY completed_at(completed_at)) {$charset};" ); dbDelta( "CREATE TABLE {$this->points_table()} (id bigint(20) unsigned NOT NULL AUTO_INCREMENT,generation_id bigint(20) unsigned NOT NULL,point_id bigint(20) unsigned NOT NULL,name varchar(255) NOT NULL,point_number varchar(100) NULL,type varchar(32) NOT NULL,full_address text NOT NULL,latitude decimal(10,7) NULL,longitude decimal(10,7) NULL,schedule_json longtext NOT NULL,is_active tinyint(1) NOT NULL,is_bulky tinyint(1) NOT NULL,storage_period_days int NULL,fitting_rooms_count int NULL,min_weight_g int NULL,max_weight_g int NULL,max_width_mm int NULL,max_length_mm int NULL,max_height_mm int NULL,fingerprint char(64) NOT NULL,PRIMARY KEY(id),UNIQUE KEY generation_point(generation_id,point_id),KEY generation_id(generation_id),KEY active_lookup(generation_id,is_active,type)) {$charset};" ); }
	public function start( string $job_id ): int { $this->wpdb->insert( $this->generations_table(), array( 'state' => 'building', 'job_id' => $job_id, 'started_at' => current_time( 'mysql', true ) ) ); return (int) $this->wpdb->insert_id; }
	/** @return array<string,mixed>|null */ public function generation_by_job( string $job_id ): ?array { $row = $this->wpdb->get_row( $this->wpdb->prepare( "SELECT * FROM {$this->generations_table()} WHERE job_id=%s", $job_id ), ARRAY_A ); return is_array( $row ) ? $row : null; }
	/** @return array<string,mixed>|null */ public function active_generation(): ?array { $row = $this->wpdb->get_row( "SELECT * FROM {$this->generations_table()} WHERE state='active' ORDER BY id DESC LIMIT 1", ARRAY_A ); return is_array( $row ) ? $row : null; }
	public function active_count(): int { $active = $this->active_generation(); return $active ? (int) $this->wpdb->get_var( $this->wpdb->prepare( "SELECT COUNT(*) FROM {$this->points_table()} WHERE generation_id=%d", $active['id'] ) ) : 0; }
	/** @param array<string,mixed> $row */ public function insert_point( int $generation_id, array $row ): bool { $row['generation_id'] = $generation_id; return false !== $this->wpdb->insert( $this->points_table(), $row ); }
	/** @return array<string,mixed>|null */ public function find_in_generation( int $generation_id, int $point_id ): ?array { $row = $this->wpdb->get_row( $this->wpdb->prepare( "SELECT point_id,fingerprint FROM {$this->points_table()} WHERE generation_id=%d AND point_id=%d", $generation_id, $point_id ), ARRAY_A ); return is_array( $row ) ? $row : null; }
	/** @param array<string,mixed> $patch */ public function update_generation( int $id, array $patch ): void { $this->wpdb->update( $this->generations_table(), $patch, array( 'id' => $id ) ); }
	public function fail( int $id, string $code, string $message ): void { $this->update_generation( $id, array( 'state' => 'failed', 'completed_at' => current_time( 'mysql', true ), 'safe_error_code' => substr( $code, 0, 80 ), 'safe_error_message' => substr( $message, 0, 300 ) ) ); $this->wpdb->query( $this->wpdb->prepare( "DELETE FROM {$this->points_table()} WHERE generation_id=%d", $id ) ); }
	public function activate( int $id ): bool { $generation = $this->wpdb->get_row( $this->wpdb->prepare( "SELECT * FROM {$this->generations_table()} WHERE id=%d", $id ), ARRAY_A ); if ( ! is_array( $generation ) || (int) $generation['accepted_count'] <= 0 || (int) $generation['conflict_count'] > 0 ) { return false; } $this->wpdb->query( 'START TRANSACTION' ); try { $this->wpdb->query( "UPDATE {$this->generations_table()} SET state='obsolete' WHERE state='active'" ); $this->wpdb->update( $this->generations_table(), array( 'state' => 'active', 'completed_at' => current_time( 'mysql', true ) ), array( 'id' => $id ) ); $this->wpdb->query( 'COMMIT' ); return true; } catch ( \Throwable ) { $this->wpdb->query( 'ROLLBACK' ); return false; } }
	/** @return array<string,mixed>|null */ public function find_active( int $point_id ): ?array { $active = $this->active_generation(); if ( ! $active ) { return null; } $row = $this->wpdb->get_row( $this->wpdb->prepare( "SELECT * FROM {$this->points_table()} WHERE generation_id=%d AND point_id=%d", $active['id'], $point_id ), ARRAY_A ); return is_array( $row ) ? $row : null; }
}
